import test from 'node:test';import assert from 'node:assert/strict';import {io} from 'socket.io-client';import {createTimefallApp} from '../dist-server/server/app.js';import {blocked} from '../shared/collision.js';import {COLLIDERS} from '../dist-server/shared/world-map.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(t,{automatic=false,graceMs=1000}={}){let now=10000;const runtime=createTimefallApp({manual:!automatic,clock:automatic?Date.now:()=>now,graceMs});const port=await runtime.listen(0);const clients=[],sessions=new Map();t.after(async()=>{for(const s of clients)s.disconnect();await runtime.close();});
 const open=async()=>{const s=io(`http://127.0.0.1:${port}`,{transports:['websocket'],reconnection:false,forceNew:true});clients.push(s);await new Promise((r,j)=>{s.once('connect',r);s.once('connect_error',j);});return s;};
 const emit=async(s,event,payload)=>{const reply=await s.timeout(1500).emitWithAck(event,payload);if(reply.ok&&reply.session)sessions.set(s,reply.session);return reply;};
 const state=s=>runtime.manager.state(sessions.get(s).code);const me=s=>state(s).players.find(p=>p.id===sessions.get(s).playerId);
 const step=(ms=50)=>{now+=ms;runtime.step();};
 const create=async(s,nickname='Alpha')=>{const reply=await emit(s,'room:create',{nickname});assert.ok(reply.ok,reply.error);return reply;};
 const join=async(s,code,nickname='Beta')=>{const reply=await emit(s,'room:join',{nickname,code});assert.ok(reply.ok,reply.error);return reply;};
 const two=async()=>{const a=await open(),b=await open(),r=await create(a);await join(b,r.session.code);return {a,b,code:r.session.code};};
 const start=async(a,b)=>{await emit(a,'room:ready',{ready:true,epoch:state(a).epoch});await emit(b,'room:ready',{ready:true,epoch:state(a).epoch});const r=await emit(a,'room:start',{epoch:state(a).epoch});assert.ok(r.ok,r.error);return r;};
 const walk=async(s,x,z,count)=>{for(let i=0;i<count;i++){const r=await emit(s,'player:input',{epoch:state(s).epoch,seq:me(s).lastSeq+1,x,z});assert.ok(r.ok,r.error);step();}};
 const interact=async(s,target='beacon',requestId='scan-request-001',version=state(s).objective.version,epoch=state(s).epoch)=>emit(s,'objective:interact',{target,requestId,objectiveVersion:version,epoch});
 return {runtime,port,open,emit,state,me,step,create,join,two,start,walk,interact,sessions,advance:ms=>{now+=ms;},unlock:()=>step(4600)};
}
function expectError(reply,error){assert.equal(reply.ok,false);assert.equal(reply.error,error);}

const cases={};
const internal=(f,s)=>f.runtime.manager.rooms.get(f.state(s).code).players.get(f.me(s).id);
const room=(f,s)=>f.runtime.manager.rooms.get(f.state(s).code);
const at=(f,s,x,z)=>Object.assign(internal(f,s),{x,z});
const act=(f,s,kind,target,extra={})=>f.emit(s,'facility:action',{epoch:f.state(s).epoch,eventId:f.state(s).facility.id,requestId:crypto.randomUUID(),kind,target,...extra});
async function active(f){const q=await f.two();await f.start(q.a,q.b);f.unlock();room(f,q.a).objective.stage=2;room(f,q.a).survival.event.status='success';return q;}
async function enter(f,a,b){at(f,a,-4,-42);at(f,b,4,-42);assert.ok((await act(f,a,'sync','west')).ok);assert.ok((await act(f,b,'sync','east')).ok);}
async function cipher(f,a,b){await enter(f,a,b);at(f,a,-6,-62);at(f,b,6,-62);await act(f,a,'read','alpha');await act(f,b,'read','beta');at(f,a,0,-64);const obs=f.state(a).facility.observations;assert.ok((await act(f,a,'solve',obs.find(c=>c.channel==='alpha').glyph+'-'+obs.find(c=>c.channel==='beta').glyph)).ok);}
cases['01 fresh facility reset defaults']=async f=>{const {a}=await active(f);assert.equal(f.state(a).facility.stage,0);assert.equal(f.state(a).facility.scanner,'active');assert.equal(f.state(a).facility.collected.length,0);};
cases['02 M3 and survey prerequisites server enforced']=async f=>{const {a}=await active(f);room(f,a).objective.stage=1;at(f,a,-4,-42);expectError(await act(f,a,'sync','west'),'FACILITY_LOCKED');};
cases['03 unresolved security blocks entry']=async f=>{const {a}=await active(f);room(f,a).survival.event.status='idle';at(f,a,-4,-42);expectError(await act(f,a,'sync','west'),'FACILITY_LOCKED');};
cases['04 proximity validates entry']=async f=>{const {a}=await active(f);expectError(await act(f,a,'sync','west'),'OUT_OF_RANGE');};
cases['05 distinct operators synchronize within window']=async f=>{const {a,b}=await active(f);await enter(f,a,b);assert.equal(f.state(a).facility.stage,1);};
cases['06 one player cannot spoof both entry stations']=async f=>{const {a}=await active(f);at(f,a,-4,-42);await act(f,a,'sync','west');at(f,a,4,-42);await act(f,a,'sync','east');assert.equal(f.state(a).facility.stage,0);};
cases['07 same station unavailable to second operator']=async f=>{const {a,b}=await active(f);at(f,a,-4,-42);at(f,b,-4,-42);await act(f,a,'sync','west');expectError(await act(f,b,'sync','west'),'ROLE_TAKEN');};
cases['08 expired sync window does not open']=async f=>{const {a,b}=await active(f);at(f,a,-4,-42);at(f,b,4,-42);await act(f,a,'sync','west');f.step(8001);await act(f,b,'sync','east');assert.equal(f.state(a).facility.stage,0);};
cases['09 disconnected entry operator invalidated']=async f=>{const {a,b}=await active(f);at(f,a,-4,-42);at(f,b,4,-42);await act(f,a,'sync','west');f.runtime.manager.disconnect(a.id);await act(f,b,'sync','east');assert.equal(f.state(b).facility.stage,0);};
cases['10 incapacitated operator cannot activate']=async f=>{const {a}=await active(f);internal(f,a).health=0;expectError(await act(f,a,'sync','west'),'INCAPACITATED');};
cases['11 leaving station invalidates activation']=async f=>{const {a,b}=await active(f);at(f,a,-4,-42);await act(f,a,'sync','west');at(f,a,-4,-38);at(f,b,4,-42);await act(f,b,'sync','east');assert.equal(f.state(a).facility.stage,0);};
cases['12 distributed clues different operators']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-62);await act(f,a,'read','alpha');at(f,a,6,-62);expectError(await act(f,a,'read','beta'),'DUPLICATE_CONTRIBUTION');};
cases['13 cipher needs both observations']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,0,-64);expectError(await act(f,a,'solve','SOL-LUNA'),'NEED_TEAMMATE');};
cases['14 combined clues unlock research wing']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);assert.equal(f.state(a).facility.stage,2);};
cases['15 wrong cipher damages operator and alerts team']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-62);at(f,b,6,-62);await act(f,a,'read','alpha');await act(f,b,'read','beta');at(f,a,0,-64);await act(f,a,'solve','SOL-SOL');assert.equal(f.me(a).health,92);assert.equal(f.state(a).survival.alert,5);assert.equal(f.state(a).facility.stage,1);};
cases['16 cache collects once concurrently']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-53);at(f,b,-6,-53);const r=await Promise.all([act(f,a,'collect','facility-cell'),act(f,b,'collect','facility-cell')]);assert.equal(r.filter(v=>v.ok).length,1);assert.equal(f.state(a).survival.energy,48);};
cases['17 cache distance validated']=async f=>{const {a,b}=await active(f);await enter(f,a,b);expectError(await act(f,a,'collect','facility-cell'),'OUT_OF_RANGE');};
cases['18 cache medical capped']=async f=>{const {a,b}=await active(f);await enter(f,a,b);internal(f,a).health=90;at(f,a,-6,-76);await act(f,a,'collect','facility-med');assert.equal(f.me(a).health,100);};
cases['19 scanner detects damages and alerts']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,0,-60);f.step();assert.equal(f.me(a).health,88);assert.equal(f.state(a).survival.alert,2);};
cases['20 scanner avoidance sides incurs no damage']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,6,-60);f.step();assert.equal(f.me(a).health,100);};
cases['21 scanner disable spends once']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-56);await act(f,a,'scanner','disable');expectError(await act(f,a,'scanner','disable'),'EVENT_RESOLVED');assert.equal(f.state(a).survival.resources,0);at(f,a,0,-60);f.step();assert.equal(f.me(a).health,100);};
cases['22 scanner distraction expires by server clock']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-56);await act(f,a,'scanner','distract');at(f,a,0,-60);f.step();assert.equal(f.me(a).health,100);f.step(20001);assert.equal(f.me(a).health,88);};
cases['23 power route resource cost once']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);await act(f,a,'route','energy');expectError(await act(f,a,'route','energy'),'EVENT_RESOLVED');assert.equal(f.state(a).survival.energy,18);};
cases['24 insufficient materials reject without spending']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);expectError(await act(f,a,'route','materials'),'INSUFFICIENT_SUPPLIES');assert.equal(f.state(a).facility.routing,null);};
cases['25 overload preserves reserves damages whole team']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);await act(f,a,'route','overload');assert.deepEqual(f.state(a).players.map(p=>p.health),[85,85]);assert.equal(f.state(a).survival.alert,15);};
cases['26 separate power contributions unlock checkpoint']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);await act(f,a,'route','energy');at(f,a,-5,-90);at(f,b,5,-90);await act(f,a,'power','generator');await act(f,b,'power','relay');assert.equal(f.state(a).facility.stage,3);};
cases['27 one player cannot contribute both power roles']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);await act(f,a,'route','energy');at(f,a,-5,-90);await act(f,a,'power','generator');at(f,a,5,-90);expectError(await act(f,a,'power','relay'),'DUPLICATE_CONTRIBUTION');};
cases['28 patrol damage and diversion']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,Math.sin(f.state(a).serverTime/1800)*4,-86);f.step();assert.equal(f.me(a).health,82);at(f,a,6,-78);await act(f,a,'patrol','divert');assert.equal(f.state(a).survival.energy,20);at(f,a,0,-86);f.step(3000);assert.equal(f.me(a).health,82);};
cases['29 malformed stats and targets rejected']=async f=>{const {a}=await active(f);expectError(await act(f,a,'sync','west',{health:999}),'BAD_PAYLOAD');expectError(await act(f,a,'unlock','all'),'BAD_PAYLOAD');at(f,a,0,-42);expectError(await act(f,a,'sync','other'),'INVALID_TARGET');};
cases['30 stale run event and request rejected']=async f=>{const {a}=await active(f);at(f,a,-4,-42);expectError(await act(f,a,'sync','west',{eventId:'stale'}),'STALE_EVENT');const requestId='request-m4-duplicate';await act(f,a,'sync','west',{requestId});expectError(await act(f,a,'sync','west',{requestId}),'DUPLICATE_ACTION');};
cases['31 reconnect preserves clues and unique identity']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-62);await act(f,a,'read','alpha');const session=f.sessions.get(a);a.disconnect();await wait(20);const c=await f.open();await f.emit(c,'room:resume',{code:session.code,token:session.token});assert.equal(f.me(c).id,session.playerId);assert.equal(f.state(b).players.length,2);assert.equal(f.state(c).facility.observations[0].playerId,session.playerId);};
cases['32 reservation expiry clears absent clue owner']=async f=>{const {a,b}=await active(f);await enter(f,a,b);at(f,a,-6,-62);await act(f,a,'read','alpha');a.disconnect();await wait(20);f.step(1001);assert.equal(f.state(b).facility.observations.length,0);at(f,b,-6,-62);assert.ok((await act(f,b,'read','alpha')).ok);at(f,b,6,-62);assert.ok((await act(f,b,'read','beta')).ok);};
cases['33 expired second operator does not block reactor']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);await act(f,a,'route','energy');at(f,a,-5,-90);await act(f,a,'power','generator');b.disconnect();await wait(20);f.step(1001);assert.equal(f.state(a).facility.stage,3);};
cases['34 separate rooms progress independently']=async f=>{const q=await active(f),r=await active(f);await enter(f,q.a,q.b);assert.equal(f.state(r.a).facility.stage,0);expectError(await act(f,q.a,'collect','facility-cell',{code:r.code}),'BAD_PAYLOAD');};
cases['35 reset clears facility epoch clues hazards and supplies']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);const id=f.state(a).facility.id;await f.emit(a,'room:reset',{epoch:1});assert.equal(f.state(a).facility.stage,0);assert.equal(f.state(a).facility.observations.length,0);assert.equal(f.state(a).facility.collected.length,0);assert.notEqual(f.state(a).facility.id,id);assert.equal(f.state(a).facility.scanner,'active');};
cases['36 door collision blocks premature north movement']=async f=>{const {a}=await active(f);at(f,a,0,-44);await f.walk(a,0,-1,30);assert.ok(f.me(a).z>-45.1);};
cases['37 host transfer continues facility']=async f=>{const {a,b}=await active(f);await enter(f,a,b);const id=f.me(b).id;a.disconnect();await wait(20);assert.equal(f.state(b).hostId,id);assert.equal(f.state(b).facility.stage,1);};
cases['38 third player can contribute without increasing required count']=async f=>{const {a,b,code}=await f.two();const c=await f.open();await f.join(c,code,'Gamma');await f.emit(c,'room:ready',{ready:true,epoch:0});await f.start(a,b);f.unlock();room(f,a).objective.stage=2;room(f,a).survival.event.status='success';await enter(f,a,c);assert.equal(f.state(b).facility.stage,1);};
cases['39 incapacitated reactor contributor cannot complete remotely']=async f=>{const {a,b}=await active(f);await cipher(f,a,b);at(f,a,-5,-84);await act(f,a,'route','energy');at(f,a,-5,-90);await act(f,a,'power','generator');internal(f,a).health=0;at(f,b,5,-90);await act(f,b,'power','relay');assert.equal(f.state(b).facility.stage,2);assert.equal(f.state(b).facility.contributions.length,1);};
cases['40 sync remaining operator unlocks after expired reservation']=async f=>{const {a,b}=await active(f);at(f,a,-4,-42);await act(f,a,'sync','west');b.disconnect();await wait(20);f.step(1001);f.step();assert.equal(f.state(a).facility.stage,1);};
for(const [name,run] of Object.entries(cases))test('M4 '+name,async t=>run(await fixture(t)));
