import test from 'node:test';import assert from 'node:assert/strict';import {io} from 'socket.io-client';import {createTimefallApp} from '../dist-server/server/app.js';import {blocked} from '../shared/collision.js';import {COLLIDERS} from '../dist-server/shared/world-map.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(t,{automatic=false,graceMs=1000}={}){let now=10000;const runtime=createTimefallApp({manual:!automatic,clock:automatic?Date.now:()=>now,graceMs});const port=await runtime.listen(0);const clients=[],sessions=new Map();t.after(async()=>{for(const s of clients)s.disconnect();await runtime.close();});
 const open=async()=>{const s=io(`http://127.0.0.1:${port}`,{transports:['websocket'],reconnection:false,forceNew:true});clients.push(s);await new Promise((r,j)=>{s.once('connect',r);s.once('connect_error',j);});return s;};
 const emit=async(s,event,payload)=>{const reply=await s.timeout(1500).emitWithAck(event,payload);if(reply.ok&&reply.session)sessions.set(s,reply.session);return reply;};
 const state=s=>runtime.manager.state(sessions.get(s).code);const me=s=>state(s).players.find(p=>p.id===sessions.get(s).playerId);
 const step=(ms=50)=>{now+=ms;runtime.step();};
 const create=async(s,nickname='Alpha')=>{const reply=await emit(s,'room:create',{nickname});assert.ok(reply.ok,reply.error);return reply;};
 const join=async(s,code,nickname='Beta')=>{const reply=await emit(s,'room:join',{nickname,code});assert.ok(reply.ok,reply.error);return reply;};
 const two=async()=>{const a=await open(),b=await open(),r=await create(a);await join(b,r.session.code);return {a,b,code:r.session.code};};
 const start=async(a,b)=>{await emit(a,'room:ready',{ready:true,epoch:state(a).epoch});await emit(b,'room:ready',{ready:true,epoch:state(a).epoch});const r=await emit(a,'room:start',{epoch:state(a).epoch});assert.ok(r.ok,r.error);return r;};
 const walk=async(s,x,z,count)=>{for(let i=0;i<count;i++){const r=await emit(s,'player:input',{epoch:state(s).epoch,seq:me(s).lastSeq+1,x,z});assert.ok(r.ok,r.error);step();}};
 const interact=async(s,target='beacon',requestId='scan-request-001',version=state(s).objective.version,epoch=state(s).epoch)=>emit(s,'objective:interact',{target,requestId,objectiveVersion:version,epoch});
 return {runtime,port,open,emit,state,me,step,create,join,two,start,walk,interact,sessions,unlock:()=>step(4600)};
}
function expectError(reply,error){assert.equal(reply.ok,false);assert.equal(reply.error,error);}
const cases={
 '01 creates a short unambiguous room and opaque private session':async f=>{const a=await f.open(),r=await f.create(a);assert.match(r.session.code,/^[23456789ABCDEFGHJKMNPQRSTVWXYZ]{5}$/);assert.equal(r.session.token.length,43);assert.equal(r.state.hostId,r.session.playerId);assert.ok(!JSON.stringify(r.state).includes(r.session.token));},
 '02 second client joins with case-insensitive code':async f=>{const a=await f.open(),b=await f.open(),r=await f.create(a);await f.join(b,r.session.code.toLowerCase());assert.equal(f.state(a).players.length,2);},
 '03 invalid room code is rejected':async f=>{const a=await f.open();expectError(await f.emit(a,'room:join',{nickname:'Beta',code:'00000'}),'BAD_PAYLOAD');},
 '04 missing room is rejected':async f=>{const a=await f.open();expectError(await f.emit(a,'room:join',{nickname:'Beta',code:'AAAAA'}),'ROOM_NOT_FOUND');},
 '05 six slots are allowed and a seventh is rejected':async f=>{const a=await f.open(),r=await f.create(a);for(let i=0;i<5;i++)await f.join(await f.open(),r.session.code,'P'+i);expectError(await f.emit(await f.open(),'room:join',{nickname:'Seventh',code:r.session.code}),'ROOM_FULL');assert.equal(f.state(a).players.length,6);},
 '06 empty nickname is rejected':async f=>{expectError(await f.emit(await f.open(),'room:create',{nickname:'   '}),'BAD_PAYLOAD');},
 '07 long nickname is rejected':async f=>{expectError(await f.emit(await f.open(),'room:create',{nickname:'x'.repeat(17)}),'BAD_PAYLOAD');},
 '08 control characters and markup nicknames are rejected':async f=>{const a=await f.open();for(const nickname of ['A\u0000B','<script>','\n'])expectError(await f.emit(a,'room:create',{nickname}),'BAD_PAYLOAD');},
 '09 duplicate nicknames keep independent IDs and colors':async f=>{const a=await f.open(),b=await f.open(),r=await f.create(a,'Same');await f.join(b,r.session.code,'Same');assert.notEqual(f.me(a).id,f.me(b).id);assert.notEqual(f.me(a).color,f.me(b).color);},
 '10 ready and unready propagate over Socket.IO':async f=>{const {a,b}=await f.two();let latest;b.on('room:state',s=>latest=s);await f.emit(a,'room:ready',{ready:true,epoch:0});await wait(10);assert.equal(latest.players.find(p=>p.id===f.me(a).id).ready,true);await f.emit(a,'room:ready',{ready:false,epoch:0});await wait(10);assert.equal(latest.players.find(p=>p.id===f.me(a).id).ready,false);},
 '11 start needs two connected players':async f=>{const a=await f.open();await f.create(a);await f.emit(a,'room:ready',{ready:true,epoch:0});expectError(await f.emit(a,'room:start',{epoch:0}),'TOO_FEW_PLAYERS');},
 '12 start requires readiness':async f=>{const {a}=await f.two();expectError(await f.emit(a,'room:start',{epoch:0}),'NOT_READY');},
 '13 only host can start':async f=>{const {b}=await f.two();expectError(await f.emit(b,'room:start',{epoch:0}),'NOT_HOST');},
 '14 both clients receive identical authoritative start/arrival':async f=>{const {a,b}=await f.two();let received;b.on('room:state',s=>received=s);const r=await f.start(a,b);await wait(10);assert.equal(received.phase,'playing');assert.equal(received.epoch,r.state.epoch);assert.equal(received.startedAt,r.state.startedAt);assert.deepEqual(received.players,r.state.players);},
 '15 movement is rejected during synchronized arrival':async f=>{const {a,b}=await f.two();await f.start(a,b);expectError(await f.emit(a,'player:input',{epoch:1,seq:1,x:0,z:-1}),'ARRIVING');},
 '16 players move independently':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();const beforeA=f.me(a),beforeB=f.me(b);await f.walk(a,0,-1,10);assert.ok(f.me(a).z<beforeA.z);assert.equal(f.me(b).z,beforeB.z);await f.walk(b,1,0,10);assert.ok(f.me(b).x>beforeB.x);assert.equal(f.me(a).x,beforeA.x);},
 '17 remote position snapshots reflect server movement':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();let latest;b.on('room:state',s=>latest=s);await f.walk(a,0,-1,10);f.step();await wait(10);assert.equal(latest.players.find(p=>p.id===f.me(a).id).z,f.me(a).z);},
 '18 arbitrary positions and excess movement magnitudes are rejected':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();for(const data of [{x:500,z:0},{x:1,z:1},{x:0,z:-1,position:{x:900,z:900}}])expectError(await f.emit(a,'player:input',{epoch:1,seq:1,...data}),'BAD_PAYLOAD');assert.equal(f.me(a).z,11);},
 '19 old and duplicate movement sequences are rejected':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,1);expectError(await f.emit(a,'player:input',{epoch:1,seq:1,x:0,z:-1}),'STALE_INPUT');},
 '20 movement stays inside outer world boundaries':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,-1,0,160);assert.ok(f.me(a).x>=-21.58);assert.equal(blocked(f.me(a).x,f.me(a).z,COLLIDERS),false);},
 '21 authoritative building collision prevents penetration':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,100);await f.walk(a,1,0,120);assert.ok(f.me(a).x<=10.08+.001);assert.equal(blocked(f.me(a).x,f.me(a).z,COLLIDERS),false);},
 '22 shared beacon objective synchronizes over real sockets':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);let latest;b.on('room:state',s=>latest=s);assert.ok((await f.interact(a)).ok);await wait(10);assert.equal(latest.objective.stage,1);assert.deepEqual(f.state(a).objective,f.state(b).objective);},
 '23 out-of-range interaction is rejected':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();expectError(await f.interact(a),'OUT_OF_RANGE');assert.equal(f.state(a).objective.stage,0);},
 '24 duplicate interaction is rejected without double advancement':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);assert.ok((await f.interact(a)).ok);expectError(await f.interact(a,'beacon','scan-request-001',0),'DUPLICATE_ACTION');assert.equal(f.state(a).objective.stage,1);},
 '25 stale objective requests are rejected':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);await f.interact(a);expectError(await f.interact(b,'beacon','different-request',0),'STALE_OBJECTIVE');},
 '26 malformed packets are safely rejected':async f=>{const a=await f.open();for(const payload of [null,{},'text',[],{nickname:3},{nickname:'Alpha',extra:true}])expectError(await f.emit(a,'room:create',payload),'BAD_PAYLOAD');assert.equal(f.runtime.manager.rooms.size,0);},
 '27 action targeting another player is rejected':async f=>{const {a,b}=await f.two();expectError(await f.emit(a,'room:ready',{ready:true,epoch:0,playerId:f.me(b).id}),'BAD_PAYLOAD');assert.equal(f.me(b).ready,false);},
 '28 outsider cannot perform room/player operations':async f=>{const a=await f.open();expectError(await f.emit(a,'room:start',{epoch:0}),'NOT_JOINED');expectError(await f.emit(a,'player:input',{epoch:0,seq:1,x:0,z:0}),'NOT_JOINED');},
 '29 two rooms isolate membership, movement, objectives and forged targeting':async f=>{const one=await f.two(),two=await f.two();await f.start(one.a,one.b);await f.start(two.a,two.b);f.unlock();const seenA=[],seenB=[];one.b.on('room:state',s=>seenA.push(s));two.b.on('room:state',s=>seenB.push(s));await f.walk(one.a,0,-1,77);await f.interact(one.a);f.step();await wait(10);assert.equal(f.state(two.a).objective.stage,0);assert.equal(f.me(two.a).z,11);for(const s of seenA){assert.equal(s.code,one.code);assert.ok(s.players.every(p=>!f.state(two.a).players.some(q=>q.id===p.id)));}for(const s of seenB)assert.equal(s.code,two.code);expectError(await f.emit(one.a,'player:input',{epoch:1,seq:99,x:0,z:0,code:two.code}),'BAD_PAYLOAD');assert.equal(f.state(two.a).objective.stage,0);},
 '30 disconnect reserves identity, state and slot':async f=>{const {a,b}=await f.two();const id=f.me(a).id;a.disconnect();await wait(10);const p=f.state(b).players.find(p=>p.id===id);assert.equal(p.connected,false);assert.equal(p.x,-1.7);assert.equal(f.state(b).players.length,2);},
 '31 reconnect restores identity, position and shared objective':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);await f.interact(a);const before=f.me(a),session=f.sessions.get(a);a.disconnect();await wait(10);const c=await f.open(),r=await f.emit(c,'room:resume',{code:session.code,token:session.token});assert.ok(r.ok);assert.equal(r.session.playerId,before.id);assert.equal(f.me(c).z,before.z);assert.equal(f.state(c).objective.stage,1);assert.equal(f.state(c).players.length,2);},
 '32 one token cannot control simultaneous active copies':async f=>{const {a}=await f.two(),session=f.sessions.get(a),c=await f.open();expectError(await f.emit(c,'room:resume',{code:session.code,token:session.token}),'SESSION_ACTIVE');assert.equal(f.state(a).players.length,2);},
 '33 invalid and wrong-room reconnect tokens are rejected':async f=>{const {a}=await f.two(),session=f.sessions.get(a),c=await f.open();expectError(await f.emit(c,'room:resume',{code:session.code,token:'A'.repeat(43)}),'INVALID_SESSION');expectError(await f.emit(c,'room:resume',{code:'AAAAA',token:session.token}),'INVALID_SESSION');},
 '34 host transfers on disconnect and original host does not reclaim it':async f=>{const {a,b}=await f.two(),session=f.sessions.get(a),bid=f.me(b).id;a.disconnect();await wait(10);assert.equal(f.state(b).hostId,bid);const c=await f.open();await f.emit(c,'room:resume',{code:session.code,token:session.token});assert.equal(f.state(c).hostId,bid);expectError(await f.emit(c,'room:start',{epoch:0}),'NOT_HOST');},
 '35 host transfers on explicit leave':async f=>{const {a,b}=await f.two(),bid=f.me(b).id;assert.ok((await f.emit(a,'room:leave',{})).ok);assert.equal(f.state(b).hostId,bid);assert.equal(f.state(b).players.length,1);},
 '36 grace expiry removes reserved player and invalidates session':async f=>{const {a,b}=await f.two(),session=f.sessions.get(a);a.disconnect();await wait(10);f.step(1100);assert.equal(f.state(b).players.length,1);const c=await f.open();expectError(await f.emit(c,'room:resume',{code:session.code,token:session.token}),'INVALID_SESSION');},
 '37 final grace expiry tears down empty room and sessions':async f=>{const {a,b}=await f.two();a.disconnect();b.disconnect();await wait(10);f.step(1100);assert.equal(f.runtime.manager.rooms.size,0);assert.equal(f.runtime.manager.sessions.size,0);assert.equal(f.runtime.manager.sockets.size,0);},
 '38 explicit leave tears down last member room':async f=>{const a=await f.open();await f.create(a);await f.emit(a,'room:leave',{});assert.equal(f.runtime.manager.rooms.size,0);assert.equal(f.runtime.manager.sessions.size,0);},
 '39 reset clears objective, readiness, positions, inputs and stale epoch':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);await f.interact(a);assert.ok((await f.emit(a,'room:reset',{epoch:1})).ok);const state=f.state(a);assert.equal(state.phase,'lobby');assert.deepEqual(state.objective,{stage:0,version:0});assert.equal(state.startedAt,0);assert.ok(state.players.every(p=>!p.ready&&p.lastSeq===0&&p.appliedSeq===0));assert.equal(f.me(a).z,11);expectError(await f.emit(a,'player:input',{epoch:1,seq:2,x:0,z:-1}),'STALE_EPOCH');expectError(await f.interact(a,'beacon','scan-request-001',0,1),'STALE_EPOCH');await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);assert.ok((await f.interact(a,'beacon','scan-request-001')).ok);},
 '40 burst inputs cannot accelerate server movement; limiter rejects excess':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();const before=f.me(a);let rejected=0;for(let i=1;i<=120;i++){const r=await f.emit(a,'player:input',{epoch:1,seq:i,x:0,z:-1});if(!r.ok&&r.error==='RATE_LIMIT')rejected++;}for(let i=0;i<20;i++)f.step();assert.ok(before.z-f.me(a).z<=.881);assert.ok(rejected>0);},
 '41 disconnected player cannot block ready/start participation':async f=>{const {a,b,code}=await f.two(),c=await f.open();await f.join(c,code,'Gamma');c.disconnect();await wait(10);assert.ok((await f.start(a,b)).ok);},
 '42 late joins into started room are rejected':async f=>{const {a,b,code}=await f.two();await f.start(a,b);expectError(await f.emit(await f.open(),'room:join',{nickname:'Late',code}),'ROOM_STARTED');},
 '43 NaN, infinity and malformed movement do not corrupt state':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();for(const data of [{x:NaN,z:0},{x:Infinity,z:0},{x:'1',z:0},{x:0,z:0,seq:-1}])expectError(await f.emit(a,'player:input',{epoch:1,seq:1,...data}),'BAD_PAYLOAD');assert.ok(Number.isFinite(f.me(a).x));},
 '44 new room after leave uses a new independent identity':async f=>{const a=await f.open(),old=await f.create(a);await f.emit(a,'room:leave',{});const next=await f.create(a);assert.notEqual(old.session.playerId,next.session.playerId);assert.notEqual(old.session.token,next.session.token);},
 '45 shared signal/barrier progression completes for both players':async f=>{const {a,b}=await f.two();await f.start(a,b);f.unlock();await f.walk(a,0,-1,77);await f.interact(a);await f.walk(a,0,-1,130);assert.ok((await f.interact(a,'signal','signal-request-001')).ok);assert.equal(f.state(b).objective.stage,2);}
};
for(const [name,fn] of Object.entries(cases))test(name,async t=>fn(await fixture(t)));
test('46 actual running server emits about ten snapshots per second',async t=>{const f=await fixture(t,{automatic:true});const {a,b}=await f.two();await f.start(a,b);let count=0;b.on('room:state',()=>count++);await wait(1250);assert.ok(count>=9&&count<=16,`received ${count}`);t.diagnostic(`Received ${count} snapshots in 1.25 seconds on an actual timer`);});
