import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {resolve} from 'node:path';
const base=process.env.BASE_URL;if(!base)throw new Error('BASE_URL required');const executablePath=process.env.CHROMIUM_PATH||resolve('../browser-runtime/chromium');const checks=[],errors=[],browsers=[];const pass=(n,c=true)=>{assert.ok(c,n);checks.push(n);console.log('PASS',n)};const launch=()=>chromium.launch({executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const health=await fetch(base+'/health');pass('M6 public /health returns 200',health.ok);const h=await health.json();pass('M6 public health preserves authoritative milestone',h.multiplayer===true&&h.simulationHz===20&&h.snapshotHz===10);
 const aBrowser=await launch(),bBrowser=await launch();browsers.push(aBrowser,bBrowser);const aCtx=await aBrowser.newContext({viewport:{width:960,height:640}}),bCtx=await bBrowser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const A=await aCtx.newPage(),B=await bCtx.newPage();for(const p of [A,B]){p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto(base,{waitUntil:'networkidle'});}
 pass('M6 root title is release polish',await A.title()==='TIMEFALL: 2126 — M6 Release Polish');pass('Touch viewport exposes touch mode',await B.evaluate(()=>document.body.classList.contains('touch')));
 await A.locator('#nickname').fill('Desktop');await A.locator('#submitRoom').click();await A.waitForFunction(()=>!document.querySelector('#lobby')?.hasAttribute('hidden'));const code=(await A.locator('#lobbyCode').textContent()).trim();pass('Desktop creates public room',code.length===5);
 await B.locator('#joinMode').click();await B.locator('#nickname').fill('Touch');await B.locator('#roomCode').fill(code);await B.locator('#submitRoom').click();await B.waitForFunction(()=>!document.querySelector('#lobby')?.hasAttribute('hidden'));pass('Independent touch browser joins same room',(await B.locator('#lobbyCode').textContent()).trim()===code);
 await A.locator('#readyButton').click();await B.locator('#readyButton').click();await A.waitForFunction(()=>window.__M6.network.state.players.every(p=>p.ready));await A.locator('#startGame').click();await A.waitForFunction(()=>window.__M6.started);await B.waitForFunction(()=>window.__M6.started);pass('Two independent browsers start synchronized expedition');
 await A.locator('#help').click();pass('Field Guide onboarding is reopenable',await A.locator('#helpDialog').evaluate(e=>e.hasAttribute('open'))&&await A.locator('.tutorial-cards').isVisible());
 await A.locator('#masterVolume').fill('0.4');await A.locator('#ambienceVolume').fill('0.2');await A.locator('#sfxVolume').fill('0.3');pass('Independent audio sliders update client settings',await A.evaluate(()=>window.__M6.audio.master===.4&&window.__M6.audio.ambience===.2&&window.__M6.audio.sfx===.3));
 await A.locator('#muteAudio').check();pass('Mute control updates accessible audio state',await A.evaluate(()=>window.__M6.audio.muted)&&await A.locator('#muteQuick').getAttribute('aria-pressed')==='true');
 await A.locator('#reduceMotion').check();pass('Reduced motion toggles semantic body state',await A.evaluate(()=>window.__M6.reducedMotion&&document.body.classList.contains('reduced-motion')));
 await A.locator('#cameraSensitivity').fill('1.4');pass('Camera sensitivity setting applies',await A.evaluate(()=>window.__M6.cameraSensitivity===1.4));
 await A.locator('#closeHelp').click();await A.locator('#muteQuick').click();pass('Quick audio control unmutes',!await A.evaluate(()=>window.__M6.audio.muted));await A.keyboard.press('Tab');pass('Keyboard navigation produces a focused control',await A.evaluate(()=>document.activeElement instanceof HTMLButtonElement||document.activeElement instanceof HTMLInputElement));
 await B.locator('#help').click();const box=await B.locator('#helpDialog').boundingBox();pass('Mobile Field Guide fits portrait viewport',!!box&&box.x>=0&&box.x+box.width<=390&&box.y>=0&&box.y+box.height<=844);pass('Mobile audio action is touch-sized',(await B.locator('#muteQuick').boundingBox()).height>=38);await B.locator('#closeHelp').click();
 const preOfflineErrors=errors.length;pass('No serious browser console/runtime errors before forced disconnect',preOfflineErrors===0);await B.context().setOffline(true);await B.waitForFunction(()=>!window.__M6.network.connected,{timeout:20000});pass('Temporary disconnect is detected');pass('Disconnect shows reconnecting UX',await B.locator('#connectionBanner').isVisible());await B.context().setOffline(false);await B.waitForFunction(()=>window.__M6.network.connected,{timeout:20000});pass('Reconnect recovers same client session',await B.evaluate(()=>window.__M6.network.connected));
 const offlineErrors=errors.slice(preOfflineErrors);const unexpected=offlineErrors.filter(e=>!/ERR_INTERNET_DISCONNECTED|WebSocket|network|offline/i.test(e));console.log('M6_OFFLINE_CONSOLE',JSON.stringify(offlineErrors));pass('Forced-offline console contains no unexpected runtime errors',unexpected.length===0);console.log('M6_BROWSER_SUMMARY',JSON.stringify({passed:checks.length,failed:0,errors}));
}catch(e){console.error('M6_BROWSER_FAILURE',e);process.exitCode=1}finally{await Promise.all(browsers.map(b=>b.close().catch(()=>{})));}
