import {chromium} from '@playwright/test';
import {createTimefallApp} from '../dist-server/server/app.js';
import {resolve,dirname} from 'node:path';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=resolve(process.env.BASE_URL?'evidence/staging':'evidence/local');await mkdir(out,{recursive:true});
const runtime=process.env.BASE_URL?null:createTimefallApp();const base=process.env.BASE_URL||`http://127.0.0.1:${await runtime.listen()}`;
const executablePath=process.env.CHROMIUM_PATH||resolve('../browser-runtime/chromium');
const browsers=[],errors=[],checks=[],metrics={environment:'Headless Chromium 153, SwiftShader software WebGL; no physical phone',base};
const launch=()=>chromium.launch({executablePath,...(process.env.BROWSER_PROXY?{proxy:{server:process.env.BROWSER_PROXY}}:{}),args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:dirname(executablePath),FONTCONFIG_PATH:resolve(dirname(executablePath),'fonts')}});
const record=(name,condition=true)=>{assert.ok(condition,name);checks.push({name,result:'PASS'});console.log('PASS',name);};
const view=p=>p.evaluate(()=>window.__M2);
const wait=(p,fn,arg)=>p.waitForFunction(fn,arg,{timeout:45000});
const shot=(p,name)=>p.screenshot({path:resolve(out,name+'.png')});
let A,B;
try{
 for(const mobile of [false,true]){const browser=await launch();browsers.push(browser);const context=await browser.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}:{viewport:{width:960,height:640}});const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});if(mobile)B=page;else A=page;}
 await A.goto(base);await wait(A,()=>window.__M2?.network.connected);await A.locator('#nickname').fill('Nova');await A.locator('#submitRoom').click();await A.locator('#lobby').waitFor({state:'visible'});const code=await A.locator('#lobbyCode').textContent();record('A creates a room and receives five-character code',code.length===5);
 await B.goto(base);await wait(B,()=>window.__M2?.network.connected);await B.locator('#joinMode').click();await B.locator('#nickname').fill('Echo');await B.locator('#roomCode').fill(code.toLowerCase());await B.locator('#submitRoom').click();await wait(A,()=>window.__M2.network.state.players.length===2);await wait(B,()=>window.__M2.network.state.players.length===2);record('B joins same lobby using lowercase room code');
 await shot(A,'01-lobby-A');await shot(B,'02-lobby-mobile-B');
 const aId=(await view(A)).network.playerId,bId=(await view(B)).network.playerId;record('Independent browser processes, identities and WebSocket connections',aId!==bId&&(await view(A)).network.socketId!==(await view(B)).network.socketId&&(await view(A)).network.transport==='websocket'&&(await view(B)).network.transport==='websocket');
 record('Start disabled before readiness',await A.locator('#startGame').isDisabled());await A.locator('#readyButton').click();await B.locator('#readyButton').click();await wait(A,()=>window.__M2.network.state.players.every(p=>p.ready));await A.locator('#startGame').click();await wait(A,()=>window.__M2.started&&!window.__M2.intro);await wait(B,()=>window.__M2.started&&!window.__M2.intro);record('Both clients enter synchronized 3D world', (await view(A)).network.state.startedAt===(await view(B)).network.state.startedAt);record('Each client renders exactly one distinct remote avatar',(await view(A)).remotePlayers[0].id===bId&&(await view(B)).remotePlayers[0].id===aId);
 await A.keyboard.press('e');await wait(A,()=>document.querySelector('#message').textContent.includes('closer'));record('Actual out-of-range interaction rejected; shared objective unchanged',(await view(A)).stage===0&&(await view(B)).stage===0);
 const bStart=(await view(B)).network.state.players.find(p=>p.id===bId);await A.keyboard.down('w');await A.waitForTimeout(1600);await A.keyboard.up('w');await A.waitForTimeout(500);const aMove=(await view(A)).network.state.players.find(p=>p.id===aId);await wait(B,id=>window.__M2.remotePlayers.some(p=>p.id===id&&p.z<8),aId);record('A keyboard movement reaches B; B position remains independent',aMove.z<8&&Math.abs((await view(B)).network.state.players.find(p=>p.id===bId).z-bStart.z)<.01);
 const cdp=await B.context().newCDPSession(B);const joy=await B.locator('#joystick').boundingBox();const touch=async(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});await touch('touchStart',[{x:joy.x+joy.width/2,y:joy.y+joy.height/2,id:1}]);await touch('touchMove',[{x:joy.x+joy.width/2,y:joy.y+joy.height*.15,id:1}]);await B.waitForTimeout(1400);await touch('touchEnd',[]);await B.waitForTimeout(500);record('Mobile touch joystick moves B and A observes it',(await view(A)).remotePlayers.find(p=>p.id===bId).z<8);const stop=(await view(B)).network.state.players.find(p=>p.id===bId).z;await B.waitForTimeout(500);record('Touch release stops movement',Math.abs((await view(B)).network.state.players.find(p=>p.id===bId).z-stop)<.01);
 await touch('touchStart',[{x:360,y:410,id:2}]);await touch('touchMove',[{x:190,y:410,id:2}]);await touch('touchEnd',[]);await B.waitForTimeout(500);record('Right-side touch drag rotates independent camera',(await view(B)).camera.yaw>.8&&(await view(A)).camera.yaw===0);await shot(A,'03-world-A');await shot(B,'04-world-mobile-B');
 const samples=[];await A.keyboard.down('w');for(let i=0;i<8;i++){await B.waitForTimeout(180);samples.push((await view(B)).remotePlayers.find(p=>p.id===aId).z);}await A.keyboard.up('w');record('Remote interpolation has buffered samples and intermediate moving positions',new Set(samples.map(v=>v.toFixed(3))).size>3&&(await view(B)).remotePlayers[0].history>2);metrics.remoteSamples=samples;
 await A.keyboard.down('w');await wait(A,()=>window.__M2.network.state.players.find(p=>p.id===window.__M2.network.playerId).z<-5.3);await A.keyboard.up('w');await wait(A,()=>window.__M2.ready);await A.locator('#interact').click();await wait(B,()=>window.__M2.stage===1);await wait(A,()=>window.__M2.stage===1);record('Physical beacon scan synchronizes objective and both HUDs',(await A.locator('#objective').textContent())===(await B.locator('#objective').textContent()));await shot(A,'05-shared-objective-A');await shot(B,'06-shared-objective-B');
 const savedB=(await view(B)).network.state.players.find(p=>p.id===bId);await B.goto('about:blank');await wait(A,id=>!window.__M2.network.state.players.find(p=>p.id===id).connected,bId);record('Actual browser disconnect reserves player and notifies teammate');await shot(A,'07-disconnected-B');await B.goto(base);await wait(B,id=>window.__M2.network.connected&&window.__M2.network.playerId===id,bId);record('Reconnect restores same identity, objective, position and no duplicate avatar',(await view(B)).stage===1&&(await view(B)).network.state.players.length===2&&Math.abs((await view(B)).network.state.players.find(p=>p.id===bId).z-savedB.z)<.01&&(await view(A)).remotePlayers.length===1);await shot(B,'08-reconnected-B');
 await A.goto('about:blank');await wait(B,id=>window.__M2.network.state.hostId===id,bId);record('Host disconnect transfers privileges and room continues');await shot(B,'09-host-transfer-B');await A.goto(base);await wait(A,id=>window.__M2.network.connected&&window.__M2.network.playerId===id,aId);record('Returning original host keeps identity without reclaiming host',(await view(A)).network.state.hostId===bId);
 await B.setViewportSize({width:844,height:390});await B.waitForTimeout(500);record('Orientation resize updates WebGL viewport and keeps touch controls visible',(await view(B)).viewport.width===844&&await B.locator('#joystick').isVisible());await shot(B,'10-mobile-landscape');await B.setViewportSize({width:390,height:844});
 const before=await view(A);await A.waitForTimeout(3000);const after=await view(A);metrics.desktop=after;metrics.mobile=await view(B);metrics.observedNetwork={snapshotsPerSecond:(after.network.snapshots-before.network.snapshots)/3,inputsPerSecond:(after.network.inputs-before.network.inputs)/3,receivedStateBytesPerSecond:(after.network.receivedBytes-before.network.receivedBytes)/3};
 await B.locator('#help').click();await B.locator('#reset').click();await wait(A,()=>window.__M2.network.state.phase==='lobby');record('Host reset synchronizes lobby, clears readiness and objective', (await view(A)).stage===0&&(await view(B)).network.state.players.every(p=>!p.ready)&&(await view(A)).remotePlayers.length===0);await A.locator('#readyButton').click();await B.locator('#readyButton').click();await wait(B,()=>window.__M2.network.state.players.every(p=>p.ready));await B.locator('#startGame').click();await wait(A,()=>window.__M2.started&&!window.__M2.intro);record('Play-again foundation starts a fresh synchronized round',(await view(A)).stage===0&&(await view(A)).network.state.players.find(p=>p.id===aId).z===11);
 record('No fatal console/runtime errors',errors.length===0);
}catch(e){checks.push({name:String(e.stack||e),result:'FAIL'});console.error(e);if(A)await shot(A,'failure-A').catch(()=>{});if(B)await shot(B,'failure-B').catch(()=>{});process.exitCode=1;}
finally{await writeFile(resolve(out,'browser-results.json'),JSON.stringify({checks,errors,metrics},null,2));for(const b of browsers)await b.close();if(runtime)await runtime.close();console.log(`${checks.filter(c=>c.result==='PASS').length} passed; ${checks.filter(c=>c.result==='FAIL').length} failed`);}
