import {chromium} from '@playwright/test';import {createTimefallApp} from '../dist-server/server/app.js';import {resolve,dirname} from 'node:path';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=resolve(process.env.BASE_URL?'evidence/m5-staging':'evidence/m5-local');await mkdir(out,{recursive:true});const runtime=process.env.BASE_URL?null:createTimefallApp();const base=process.env.BASE_URL||`http://127.0.0.1:${await runtime.listen()}`;const executablePath=process.env.CHROMIUM_PATH||resolve('../browser-runtime/chromium');const checks=[],errors=[],browsers=[],metrics={base,environment:'Two independent Chromium processes; SwiftShader software WebGL; desktop 960x640 and touch 390x844, not physical phones'};let A,B;
const launch=()=>chromium.launch({executablePath,...(process.env.BROWSER_PROXY?{proxy:{server:process.env.BROWSER_PROXY}}:{}),args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:dirname(executablePath),FONTCONFIG_PATH:resolve(dirname(executablePath),'fonts')}});
const v=p=>p.evaluate(()=>window.__M5);const wait=(p,fn,arg)=>p.waitForFunction(fn,arg,{timeout:65000});const shot=(p,n)=>p.screenshot({path:resolve(out,n+'.png')});const pass=(name,condition=true)=>{assert.ok(condition,name);checks.push({name,result:'PASS'});console.log('PASS',name)};
async function walk(p,key,axis,goal){await wait(p,()=>!document.querySelector('dialog[open]'));await p.keyboard.down(key);try{await wait(p,([axis,goal,key])=>{const me=window.__M5.network.prediction;return key==='w'||key==='a'?me[axis]<=goal:me[axis]>=goal},[axis,goal,key]);}finally{await p.keyboard.up(key);}await p.waitForTimeout(700);}
async function probe(p,extra={},reuse=false){return p.evaluate(async([extra,reuse])=>{const state=window.__M5.network.state,ws=window.__acceptanceSocket;const payload=reuse?{...window.__lastPortalAction}:{epoch:state.epoch,eventId:state.portal.id,requestId:crypto.randomUUID(),kind:'repair',target:'coils'};Object.assign(payload,extra);const id=900000+Math.floor(Math.random()*900000);return new Promise((resolve,reject)=>{const listener=e=>{const packet=String(e.data);if(packet.startsWith('43'+id+'[')){ws.removeEventListener('message',listener);clearTimeout(timer);resolve(JSON.parse(packet.slice(packet.indexOf('[')))[0]);}};const timer=setTimeout(()=>{ws.removeEventListener('message',listener);reject(new Error('probe acknowledgement timeout'));},8000);ws.addEventListener('message',listener);ws.send('42'+id+JSON.stringify(['portal:action',payload]));});},[extra,reuse]);}
async function reset(){await A.locator('#help').click();await A.locator('#reset').click();await wait(B,()=>window.__M5.network.state.phase==='lobby');await A.locator('#readyButton').click();await B.locator('#readyButton').click();await wait(A,()=>window.__M5.network.state.players.every(p=>p.ready));await A.locator('#startGame').click();await wait(A,()=>window.__M5.started&&!window.__M5.intro);await wait(B,()=>window.__M5.started&&!window.__M5.intro);}
try{
 for(const mobile of [false,true]){const b=await launch();browsers.push(b);const c=await b.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true}:{viewport:{width:960,height:640}});const p=await c.newPage();p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.addInitScript(()=>{const original=WebSocket.prototype.send;WebSocket.prototype.send=function(data){if(this.url.includes('/socket.io/')){window.__acceptanceSocket=this;if(typeof data==='string'&&data.startsWith('42')){const bracket=data.indexOf('[');if(bracket>=0){try{const [event,payload]=JSON.parse(data.slice(bracket));if(event==='portal:action')window.__lastPortalAction=payload;}catch{}}}}return original.call(this,data);};});if(mobile)B=p;else A=p;}
 await A.goto(base);await wait(A,()=>window.__M5?.network.connected);await A.locator('#nickname').fill('Nova');await A.locator('#submitRoom').click();await A.locator('#lobby').waitFor({state:'visible'});const code=await A.locator('#lobbyCode').textContent();await B.goto(base);await wait(B,()=>window.__M5?.network.connected);await B.locator('#joinMode').click();await B.locator('#nickname').fill('Echo');await B.locator('#roomCode').fill(code);await B.locator('#submitRoom').click();await wait(A,()=>window.__M5.network.state.players.length===2);await A.locator('#readyButton').click();await B.locator('#readyButton').click();await wait(A,()=>window.__M5.network.state.players.every(p=>p.ready));await A.locator('#startGame').click();await wait(A,()=>window.__M5.started&&!window.__M5.intro);await wait(B,()=>window.__M5.started&&!window.__M5.intro);
 const aId=(await v(A)).network.playerId,bId=(await v(B)).network.playerId;pass('Independent players enter same authoritative 3D room',aId!==bId&&(await v(A)).network.socketId!==(await v(B)).network.socketId&&(await v(A)).remotePlayers.length===1);pass('Initial survival values synchronize',JSON.stringify((await v(A)).network.state.survival)===JSON.stringify((await v(B)).network.state.survival));
 async function journey(){
 await walk(A,'w','z',2);await wait(B,id=>window.__M5.remotePlayers.find(p=>p.id===id).z<3,aId);pass('A movement reaches B while B remains independent',(await v(B)).network.state.players.find(p=>p.id===bId).z===11);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.survival.energy===50);await wait(A,()=>window.__M5.network.state.survival.energy===50);await wait(A,()=>document.querySelector('#energyValue').textContent==='50');await wait(B,()=>document.querySelector('#energyValue').textContent==='50');pass('Physical supply collection updates both HUDs',(await A.locator('#energyValue').textContent())==='50'&&(await B.locator('#energyValue').textContent())==='50');await A.keyboard.press('e');await A.waitForTimeout(350);pass('Repeat action cannot duplicate collected energy',(await v(A)).network.state.survival.energy===50);await shot(A,'01-collected-supply');
 await walk(A,'w','z',-5.4);await A.locator('#interact').click();await wait(B,()=>window.__M5.stage===1);await walk(A,'w','z',-10);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.survival.resources===4);pass('Material collection synchronizes shared reserve');await walk(A,'w','z',-17);await A.locator('#interact').click();await A.locator('[data-choice="energy"]').click();await wait(B,()=>window.__M5.network.state.survival.event.status==='active');await wait(A,()=>window.__M5.network.state.survival.event.status==='active');pass('M3 energy choice synchronizes reserve and safe drone',(await v(B)).network.state.survival.security==='disabled'&&(await v(B)).network.state.survival.energy===5);const deadline=(await v(A)).network.state.survival.event.deadline;pass('Both display the same authoritative event deadline',deadline===(await v(B)).network.state.survival.event.deadline);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.survival.event.contributors.length===1);
 await walk(B,'w','z',-17);await B.locator('#interact').click();await wait(A,()=>window.__M5.network.state.survival.event.status==='success');pass('Separate players operate WEST and EAST before timeout',(await v(A)).network.state.survival.event.contributors.length===2);await shot(A,'02-cooperative-success-A');await shot(B,'03-cooperative-success-mobile-B');

 await walk(A,'w','z',-38);await A.locator('#interact').click();await wait(B,()=>window.__M5.stage===2);pass('North survey reveals shared facility objective');
 await walk(A,'a','x',-4);await walk(A,'w','z',-42);await walk(B,'w','z',-38);await walk(B,'d','x',4);await walk(B,'w','z',-42);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.facility.sync.length===1);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.facility.stage===1);await wait(B,()=>window.__M5.network.state.facility.stage===1);pass('Two independent players synchronize separate entry stations');await shot(A,'10-facility-airlock-A');
 await walk(A,'w','z',-53);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.facility.collected.includes('facility-cell'));pass('Optional facility energy cache updates both clients',(await v(B)).network.state.survival.energy===23);await A.keyboard.press('e');await A.waitForTimeout(300);pass('Repeated normal cache interaction cannot duplicate reward',(await v(A)).network.state.survival.energy===23);
 await walk(B,'w','z',-53);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.facility.collected.includes('facility-material'));pass('Different player explores material cache');
 await walk(A,'a','x',-6);await walk(A,'w','z',-56);await walk(A,'d','x',0);await walk(A,'w','z',-60);await wait(B,id=>window.__M5.network.state.players.find(p=>p.id===id).health<100,aId);await walk(A,'s','z',-56);await walk(A,'a','x',-6);const health=(await v(A)).network.state.players.find(p=>p.id===aId).health;await wait(B,([id,h])=>window.__M5.network.state.players.find(p=>p.id===id).health===h,[aId,health]);pass('Facility scanner damage and Alert synchronize publicly',health<100&&(await v(B)).network.state.survival.alert>0);await A.locator('#interact').click();await A.locator('[data-facility-target="disable"]').click();await wait(B,()=>window.__M5.network.state.facility.scanner==='disabled');pass('Scanner disable consumes resources and synchronizes encounter');
 await walk(A,'w','z',-62);await A.locator('#interact').click();await A.locator('[data-facility-target="alpha"]').click();await wait(A,()=>window.__M5.network.state.facility.observations.length===1);await shot(A,'11-alpha-clue-A');await A.locator('#closeFacility').click();
 await walk(B,'d','x',6);await walk(B,'w','z',-62);await B.locator('#interact').tap();await B.locator('[data-facility-target="beta"]').tap();await wait(A,()=>window.__M5.network.state.facility.observations.length===2);await shot(B,'12-beta-clue-mobile-B');await B.locator('#closeFacility').tap();pass('Two explorers recover different information fragments');
 const before=(await v(B)).network.state.facility;await B.goto('about:blank');await wait(A,id=>!window.__M5.network.state.players.find(p=>p.id===id).connected,bId);await B.goto(base);await wait(B,id=>window.__M5.network.connected&&window.__M5.network.playerId===id,bId);pass('Facility reconnect preserves clues supplies and unique avatar',JSON.stringify((await v(B)).network.state.facility)===JSON.stringify(before)&&(await v(B)).network.state.players.length===2);
 await walk(A,'w','z',-64);

 await walk(A,'d','x',0);await A.locator('#interact').click();const obs=(await v(A)).network.state.facility.observations;const solution=obs.find(c=>c.channel==='alpha').glyph+'-'+obs.find(c=>c.channel==='beta').glyph;await A.locator(`[data-facility-target="${solution}"]`).click();await wait(B,()=>window.__M5.network.state.facility.stage===2);pass('Combined clues solve cipher and synchronize unlocked door');await shot(A,'13-cipher-open-A');
 await walk(A,'w','z',-70);await walk(A,'a','x',-6);await walk(A,'w','z',-76);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.facility.collected.includes('facility-med'));pass('Optional medical cache uses existing capped Health system');
 await walk(B,'s','z',-64);await walk(B,'a','x',0);await walk(B,'w','z',-70);await walk(B,'d','x',6);await walk(B,'w','z',-76);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.facility.collected.includes('facility-reserve'));await walk(B,'w','z',-78);await B.locator('#interact').tap();await B.locator('[data-facility-target="divert"]').tap();await wait(A,()=>window.__M5.network.state.facility.patrol==='diverted');pass('Second encounter patrol diversion synchronizes Energy consequence');
 await walk(A,'w','z',-84);await A.locator('#interact').click();for(const button of await A.locator('#facilityOptions button').all()){const box=await button.boundingBox();assert.ok(box.height>=44);}await A.locator('[data-facility-target="energy"]').click();await wait(B,()=>window.__M5.network.state.facility.routing==='energy');pass('Power-routing choice spends team Energy exactly once',(await v(B)).network.state.survival.energy===15); // 5+18+14-10-12=15
 await walk(A,'w','z',-90);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.facility.contributions.length===1);await walk(B,'w','z',-90);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.facility.stage===3);pass('Distinct GENERATOR and RELAY operators unlock transit checkpoint');await shot(A,'14-reactor-success-A');await shot(B,'15-reactor-success-mobile-B');
 await walk(B,'a','x',0);await walk(B,'w','z',-101);await walk(B,'d','x',6);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.facility.archive);pass('Optional portal archive rewards exploration once',(await v(A)).network.state.survival.energy===23);await B.keyboard.press('e');await B.waitForTimeout(300);pass('Archive cannot reward twice',(await v(B)).network.state.survival.energy===23);await shot(B,'16-transit-checkpoint-B');

}
 await journey();
 await A.goto('about:blank');await wait(B,id=>window.__M5.network.state.hostId===id,bId);await A.goto(base);await wait(A,id=>window.__M5.network.connected&&window.__M5.network.playerId===id,aId);pass('Host transfer preserves completed M4 progression',(await v(A)).network.state.facility.stage===3&&(await v(A)).network.state.hostId===bId);

 await A.waitForTimeout(3000);metrics.checkpointDesktop=await v(A);metrics.checkpointMobile=await v(B);
 await walk(A,'d','x',0);await walk(A,'w','z',-116);await walk(A,'a','x',-6);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.collected.includes('portal-cell'));const duplicate=await probe(A,{},true);pass('Duplicate portal request rejected',!duplicate.ok&&duplicate.error==='DUPLICATE_ACTION');pass('Portal entry through real transit route and supply sync',(await v(B)).network.state.survival.energy===43);await shot(A,'20-portal-arrival-A');
 await walk(B,'a','x',0);await walk(B,'w','z',-116);await walk(B,'d','x',6);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.portal.collected.includes('portal-material'));pass('Second player independently collects portal Materials');await A.waitForTimeout(3000);metrics.portalDesktop=await v(A);metrics.portalMobile=await v(B);const malformed=await probe(A,{health:999});pass('Portal Health injection rejected',malformed.error==='BAD_PAYLOAD');const stale=await probe(A,{eventId:'stale-event'});pass('Stale portal event rejected',stale.error==='STALE_EVENT');const foreign=await probe(A,{code:'23456'});pass('Wrong-room portal action rejected',foreign.error==='BAD_PAYLOAD');
 await walk(A,'d','x',0);await walk(A,'w','z',-118);await A.locator('#interact').click();await A.locator('[data-portal-target="stable"]').click();await wait(B,()=>window.__M5.network.state.portal.status==='CHARGING');pass('Stable portal route spends Energy on both clients',(await v(B)).network.state.survival.energy===23);await wait(A,()=>window.__M5.network.state.portal.status==='CHARGING');const portalDeadline=(await v(A)).network.state.portal.deadline;pass('Shared final countdown deadline',portalDeadline===(await v(B)).network.state.portal.deadline);const distant=await probe(A);pass('Out-of-range portal repair rejected',distant.error==='OUT_OF_RANGE');
 // Real movement into the final sentry, followed by incapacitation and nearby revive.
 await walk(A,'a','x',-6);await walk(A,'w','z',-132);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.repaired);pass('Portal coil repair synchronizes Materials spending');
 await walk(B,'w','z',-124);await walk(A,'s','z',-130);await walk(A,'d','x',0);await wait(B,id=>window.__M5.network.state.players.find(p=>p.id===id).incapacitated,aId);pass('Final AI pressure incapacitates and synchronizes Health');await walk(B,'w','z',-130);await walk(B,'a','x',1.8);await B.locator('#interact').tap();await wait(A,id=>window.__M5.network.state.players.find(p=>p.id===id).health===40,aId);pass('Teammate revival works during portal countdown');await walk(A,'a','x',-6);await walk(B,'d','x',6);await walk(B,'w','z',-132);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.portal.security==='disabled');pass('Final security disable synchronizes resource and Alert consequences');
 const saved=(await v(A)).network.state.portal;await A.goto('about:blank');await wait(B,id=>!window.__M5.network.state.players.find(p=>p.id===id).connected,aId);await A.goto(base);await wait(A,id=>window.__M5.network.connected&&window.__M5.network.playerId===id,aId);pass('Reconnect during final countdown preserves identity and deadline',(await v(A)).network.state.portal.deadline===saved.deadline&&(await v(A)).network.state.players.length===2);await shot(A,'21-portal-reconnect-A');
 await walk(A,'s','z',-124);await walk(A,'d','x',-5);await walk(B,'s','z',-124);await walk(B,'a','x',5);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.contributors.length===1);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.portal.status==='ACTIVE');pass('Two distinct coil operators activate portal');await shot(A,'22-active-portal-A');
 await walk(A,'w','z',-138);await walk(A,'d','x',0);await walk(B,'w','z',-138);await walk(B,'a','x',0);await A.locator('#interact').click();await A.locator('[data-portal-target="helix"]').click();await wait(B,()=>window.__M5.network.state.portal.votes.length===1);await B.locator('#interact').tap();await B.locator('[data-portal-target="helix"]').tap();await wait(A,()=>window.__M5.network.state.portal.decision==='helix');pass('Different explorers validate meaningful HELIX team decision');await walk(A,'w','z',-144);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.status==='RESOLVED');await wait(A,()=>window.__M5.network.state.portal.status==='RESOLVED');pass('Alternative HELIX ending synchronized canonically',(await v(A)).network.state.portal.ending.kind==='helix'&&JSON.stringify((await v(A)).network.state.portal.ending)===JSON.stringify((await v(B)).network.state.portal.ending));await shot(A,'23-helix-ending-A');await shot(B,'24-helix-ending-mobile-B');
 await B.setViewportSize({width:844,height:390});await B.waitForTimeout(500);pass('Facility landscape keeps joystick survival HUD and action visible',await B.locator('#joystick').isVisible()&&await B.locator('#survivalHUD').isVisible()&&await B.locator('#interact').isVisible());await shot(B,'17-facility-landscape-B');await B.setViewportSize({width:390,height:844});metrics.desktop=await v(A);metrics.mobile=await v(B);const previous=await v(A);await A.waitForTimeout(3000);const current=await v(A);metrics.observedNetwork={snapshotsPerSecond:(current.network.snapshots-previous.network.snapshots)/3,inputsPerSecond:(current.network.inputs-previous.network.inputs)/3,receivedStateBytesPerSecond:(current.network.receivedBytes-previous.network.receivedBytes)/3};
 const isolation=await B.evaluate(async otherCode=>{const open=()=>new Promise((resolve,reject)=>{const ws=new WebSocket(location.origin.replace('http','ws')+'/socket.io/?EIO=4&transport=websocket');let seq=0;const pending=new Map();const client={ws,state:null,emit:(event,payload)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,resolve);ws.send('42'+id+JSON.stringify([event,payload]));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('protocol acknowledgement timeout'));}},6000);})};ws.onerror=reject;ws.onmessage=e=>{const packet=String(e.data);if(packet.startsWith('0'))ws.send('40');else if(packet==='2')ws.send('3');else if(packet.startsWith('40'))resolve(client);else if(packet.startsWith('43')){const bracket=packet.indexOf('['),id=Number(packet.slice(2,bracket));pending.get(id)?.(JSON.parse(packet.slice(bracket))[0]);pending.delete(id);}else if(packet.startsWith('42')){const [event,state]=JSON.parse(packet.slice(2));if(event==='room:state')client.state=state;}};});const c=await open(),d=await open();try{const created=await c.emit('room:create',{nickname:'IsolationC'});const code=created.session.code;await d.emit('room:join',{nickname:'IsolationD',code});await c.emit('room:ready',{epoch:0,ready:true});await d.emit('room:ready',{epoch:0,ready:true});const start=await c.emit('room:start',{epoch:0});const eventId=start.state.facility.id;const malformed=await c.emit('facility:action',{epoch:1,eventId,requestId:crypto.randomUUID(),kind:'sync',target:'west',health:999});const foreign=await c.emit('facility:action',{epoch:1,eventId,requestId:crypto.randomUUID(),kind:'sync',target:'west',code:otherCode});const stale=await c.emit('facility:action',{epoch:0,eventId,requestId:crypto.randomUUID(),kind:'sync',target:'west'});return {code,stage:start.state.facility.stage,malformed:malformed.error,foreign:foreign.error,stale:stale.error};}finally{await d.emit('room:leave',{});await c.emit('room:leave',{});c.ws.close();d.ws.close();}},code);pass('Additional public room remains isolated from completed facility',isolation.code!==code&&isolation.stage===0&&(await v(A)).network.state.facility.stage===3);pass('Malformed client Health claim rejected publicly',isolation.malformed==='BAD_PAYLOAD');pass('Foreign-room facility target rejected publicly',isolation.foreign==='BAD_PAYLOAD');pass('Stale public run action rejected',isolation.stale==='STALE_EPOCH');
 await B.locator('#playAgain').tap();await wait(A,()=>window.__M5.network.state.phase==='lobby');pass('Play Again clears portal ending countdown and all M4/M3 state',(await v(A)).network.state.portal.status==='LOCKED'&&(await v(A)).network.state.portal.ending===null&&(await v(A)).network.state.portal.deadline===0&&(await v(A)).network.state.facility.stage===0&&(await v(A)).network.state.facility.collected.length===0&&(await v(A)).network.state.facility.observations.length===0&&(await v(A)).network.state.survival.energy===30);
 await A.locator('#readyButton').click();await B.locator('#readyButton').tap();await wait(B,()=>window.__M5.network.state.players.every(p=>p.ready));await B.locator('#startGame').tap();await wait(A,()=>window.__M5.started&&!window.__M5.intro);await wait(B,()=>window.__M5.started&&!window.__M5.intro);pass('Clean second run starts with original Health and supplies',(await v(A)).network.state.players.every(p=>p.health===100)&&(await v(A)).network.state.portal.collected.length===0);await journey();
 await walk(A,'d','x',0);await walk(A,'w','z',-116);await walk(A,'a','x',-6);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.collected.includes('portal-cell'));await walk(B,'a','x',0);await walk(B,'w','z',-116);await walk(B,'d','x',6);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.portal.collected.includes('portal-material'));
 await walk(A,'d','x',0);await walk(A,'w','z',-118);await A.locator('#interact').click();await A.locator('[data-portal-target="stable"]').click();await wait(B,()=>window.__M5.network.state.portal.status==='CHARGING');await walk(A,'a','x',-6);await walk(A,'w','z',-132);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.repaired);await walk(B,'w','z',-132);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.portal.security==='disabled');
 await walk(A,'s','z',-124);await walk(A,'d','x',-5);await walk(B,'s','z',-124);await walk(B,'a','x',5);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.contributors.length===1);await B.locator('#interact').tap();await wait(A,()=>window.__M5.network.state.portal.status==='ACTIVE');await walk(A,'w','z',-138);await walk(A,'d','x',0);await walk(B,'w','z',-138);await walk(B,'a','x',0);await A.locator('#interact').click();await A.locator('[data-portal-target="return"]').click();await wait(B,()=>window.__M5.network.state.portal.votes.length===1);await B.locator('#interact').tap();await B.locator('[data-portal-target="return"]').tap();await wait(A,()=>window.__M5.network.state.portal.decision==='return');await walk(A,'w','z',-144);await A.locator('#interact').click();await wait(B,()=>window.__M5.network.state.portal.status==='RESOLVED');await wait(A,()=>window.__M5.network.state.portal.status==='RESOLVED');pass('Second complete normal-play journey achieves safe return',(await v(A)).network.state.portal.ending.kind==='return'&&(await v(B)).network.state.portal.ending.players.every(p=>p.escaped));pass('Both clients receive identical successful ending',JSON.stringify((await v(A)).network.state.portal.ending)===JSON.stringify((await v(B)).network.state.portal.ending));await shot(A,'30-safe-return-A');await shot(B,'31-safe-return-mobile-B');
 pass('No serious console or runtime errors',errors.length===0);
}catch(e){checks.push({name:String(e.stack||e),result:'FAIL'});console.error(e);process.exitCode=1;if(A)await shot(A,'failure-A').catch(()=>{});if(B)await shot(B,'failure-B').catch(()=>{});}
finally{await writeFile(resolve(out,'results.json'),JSON.stringify({checks,errors,metrics},null,2));for(const b of browsers)await b.close();if(runtime)await runtime.close();console.log(`${checks.filter(c=>c.result==='PASS').length} passed; ${checks.filter(c=>c.result==='FAIL').length} failed`);}
