import test from 'node:test';import assert from 'node:assert/strict';import {io} from 'socket.io-client';import {createTimefallApp} from '../dist-server/server/app.js';import {blocked} from '../shared/collision.js';import {COLLIDERS} from '../dist-server/shared/world-map.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(t,{automatic=false,graceMs=1000}={}){let now=10000;const runtime=createTimefallApp({manual:!automatic,clock:automatic?Date.now:()=>now,graceMs});const port=await runtime.listen(0);const clients=[],sessions=new Map();t.after(async()=>{for(const s of clients)s.disconnect();await runtime.close();});
 const open=async()=>{const s=io(`http://127.0.0.1:${port}`,{transports:['websocket'],reconnection:false,forceNew:true});clients.push(s);await new Promise((r,j)=>{s.once('connect',r);s.once('connect_error',j);});return s;};
 const emit=async(s,event,payload)=>{const reply=await s.timeout(1500).emitWithAck(event,payload);if(reply.ok&&reply.session)sessions.set(s,reply.session);return reply;};
 const state=s=>runtime.manager.state(sessions.get(s).code);const me=s=>state(s).players.find(p=>p.id===sessions.get(s).playerId);
 const step=(ms=50)=>{now+=ms;runtime.step();};
 const create=async(s,nickname='Alpha')=>{const reply=await emit(s,'room:create',{nickname});assert.ok(reply.ok,reply.error);return reply;};
 const join=async(s,code,nickname='Beta')=>{const reply=await emit(s,'room:join',{nickname,code});assert.ok(reply.ok,reply.error);return reply;};
 const two=async()=>{const a=await open(),b=await open(),r=await create(a);await join(b,r.session.code);return {a,b,code:r.session.code};};
 const start=async(a,b)=>{await emit(a,'room:ready',{ready:true,epoch:state(a).epoch});await emit(b,'room:ready',{ready:true,epoch:state(a).epoch});const r=await emit(a,'room:start',{epoch:state(a).epoch});assert.ok(r.ok,r.error);return r;};
 const walk=async(s,x,z,count)=>{for(let i=0;i<count;i++){const r=await emit(s,'player:input',{epoch:state(s).epoch,seq:me(s).lastSeq+1,x,z});assert.ok(r.ok,r.error);step();}};
 const interact=async(s,target='beacon',requestId='scan-request-001',version=state(s).objective.version,epoch=state(s).epoch)=>emit(s,'objective:interact',{target,requestId,objectiveVersion:version,epoch});
 return {runtime,port,open,emit,state,me,step,create,join,two,start,walk,interact,sessions,advance:ms=>{now+=ms;},unlock:()=>step(4600)};
}
function expectError(reply,error){assert.equal(reply.ok,false);assert.equal(reply.error,error);}


const cases={};
const room=(f,s)=>f.runtime.manager.rooms.get(f.state(s).code);
const internal=(f,s)=>room(f,s).players.get(f.me(s).id);
const at=(f,s,x,z)=>Object.assign(internal(f,s),{x,z});
const act=(f,s,kind,target,extra={})=>f.emit(s,'portal:action',{epoch:f.state(s).epoch,eventId:f.state(s).portal.id,requestId:crypto.randomUUID(),kind,target,...extra});
async function active(f){const q=await f.two();await f.start(q.a,q.b);f.unlock();room(f,q.a).objective.stage=2;room(f,q.a).survival.event.status='success';room(f,q.a).survival.security='disabled';room(f,q.a).facility.stage=3;f.step();return q;}
async function charging(f,a,route='stable'){at(f,a,0,-118);assert.ok((await act(f,a,'route',route)).ok);}
async function activate(f,a,b){at(f,a,-5,-124);at(f,b,5,-124);assert.ok((await act(f,a,'stabilize','west')).ok);assert.ok((await act(f,b,'stabilize','east')).ok);assert.equal(f.state(a).portal.status,'ACTIVE');}
async function vote(f,a,b,choice='return'){at(f,a,0,-138);at(f,b,0,-138);assert.ok((await act(f,a,'vote',choice)).ok);assert.ok((await act(f,b,'vote',choice)).ok);}
cases['01 initial portal is locked']=async f=>{const {a}=await f.two();assert.equal(f.state(a).portal.status,'LOCKED');assert.equal(f.state(a).portal.ending,null);};
cases['02 facility prerequisite enforced']=async f=>{const {a}=await active(f);room(f,a).facility.stage=2;at(f,a,0,-118);expectError(await act(f,a,'route','stable'),'FACILITY_LOCKED');};
cases['03 completed facility unlocks ready']=async f=>{const {a}=await active(f);assert.equal(f.state(a).portal.status,'READY');};
cases['04 proximity enforced']=async f=>{const {a}=await active(f);expectError(await act(f,a,'route','stable'),'OUT_OF_RANGE');};
cases['05 stable route costs exactly 20 Energy']=async f=>{const {a}=await active(f);await charging(f,a);assert.equal(f.state(a).survival.energy,10);assert.equal(f.state(a).portal.status,'CHARGING');};
cases['06 insufficient Energy does not mutate']=async f=>{const {a}=await active(f);room(f,a).survival.energy=0;at(f,a,0,-118);expectError(await act(f,a,'route','stable'),'INSUFFICIENT_SUPPLIES');assert.equal(f.state(a).portal.status,'READY');};
cases['07 emergency route free alert consequence']=async f=>{const {a}=await active(f);room(f,a).survival.energy=0;await charging(f,a,'surge');assert.equal(f.state(a).portal.status,'UNSTABLE');assert.equal(f.state(a).survival.alert,15);};
cases['08 two distinct players activate']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);};
cases['09 one operator cannot spoof two roles']=async f=>{const {a}=await active(f);await charging(f,a);at(f,a,-5,-124);await act(f,a,'stabilize','west');at(f,a,5,-124);await act(f,a,'stabilize','east');assert.notEqual(f.state(a).portal.status,'ACTIVE');};
cases['10 duplicate contribution rejected']=async f=>{const {a}=await active(f);await charging(f,a);at(f,a,-5,-124);await act(f,a,'stabilize','west');expectError(await act(f,a,'stabilize','west'),'DUPLICATE_CONTRIBUTION');};
cases['11 stale event rejected']=async f=>{const {a}=await active(f);expectError(await act(f,a,'route','stable',{eventId:'previous'}),'STALE_EVENT');};
cases['12 synchronization window expires']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-5,-124);at(f,b,5,-124);await act(f,a,'stabilize','west');f.step(15001);await act(f,b,'stabilize','east');assert.equal(f.state(a).portal.status,'CHARGING');};
cases['13 charge timeout resolves stranded once']=async f=>{const {a}=await active(f);await charging(f,a);f.step(90001);assert.equal(f.state(a).portal.ending.kind,'stranded');const ending=f.state(a).portal.ending;f.step(10000);assert.deepEqual(f.state(a).portal.ending,ending);};
cases['14 late action resolves timeout before tick']=async f=>{const {a}=await active(f);await charging(f,a);f.advance(90001);at(f,a,-5,-124);expectError(await act(f,a,'stabilize','west'),'EVENT_RESOLVED');assert.equal(f.state(a).portal.ending.kind,'stranded');};
cases['15 active countdown 30s authoritative']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);assert.equal(f.state(a).portal.deadline-f.state(a).serverTime,30000);f.step(30001);assert.equal(f.state(a).portal.ending.kind,'stranded');};
cases['16 simultaneous activation cannot resolve twice']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-5,-124);at(f,b,5,-124);const r=await Promise.all([act(f,a,'stabilize','west'),act(f,b,'stabilize','east')]);assert.ok(r.every(x=>x.ok));assert.equal(f.state(a).portal.status,'ACTIVE');};
cases['17 repair spends once']=async f=>{const {a}=await active(f);await charging(f,a);at(f,a,-6,-132);await act(f,a,'repair','coils');expectError(await act(f,a,'repair','coils'),'EVENT_RESOLVED');assert.equal(f.state(a).survival.resources,0);};
cases['18 repair insufficient Materials rejected']=async f=>{const {a}=await active(f);await charging(f,a);room(f,a).survival.resources=0;at(f,a,-6,-132);expectError(await act(f,a,'repair','coils'),'INSUFFICIENT_SUPPLIES');};
cases['19 security causes damage alert and incap']=async f=>{const {a}=await active(f);await charging(f,a);internal(f,a).health=10;at(f,a,Math.sin(f.state(a).serverTime/2000)*3,-130);f.step();assert.equal(f.me(a).health,0);assert.ok(f.state(a).survival.alert>0);expectError(await act(f,a,'repair','coils'),'INCAPACITATED');};
cases['20 high Alert increases pressure']=async f=>{const {a}=await active(f);await charging(f,a);room(f,a).survival.alert=50;at(f,a,Math.sin(f.state(a).serverTime/2000)*3,-130);f.step();assert.equal(f.me(a).health,75);};
cases['21 final teammate revive restores 40']=async f=>{const {a,b}=await active(f);await charging(f,a);internal(f,a).health=0;at(f,a,-6,-132);at(f,b,-6,-132);const r=await f.emit(b,'survival:action',{epoch:1,eventId:f.state(b).survival.event.id,requestId:crypto.randomUUID(),kind:'revive',target:f.me(a).id});assert.ok(r.ok);assert.equal(f.me(a).health,40);};
cases['22 sentry disable costs and reduces Alert']=async f=>{const {a}=await active(f);await charging(f,a);room(f,a).survival.alert=20;at(f,a,6,-132);await act(f,a,'security','disable');assert.equal(f.state(a).portal.security,'disabled');assert.equal(f.state(a).survival.alert,10);};
cases['23 simultaneous supplies collected once']=async f=>{const {a,b}=await active(f);at(f,a,-6,-116);at(f,b,-6,-116);const r=await Promise.all([act(f,a,'collect','portal-cell'),act(f,b,'collect','portal-cell')]);assert.equal(r.filter(x=>x.ok).length,1);assert.equal(f.state(a).survival.energy,50);};
cases['24 medical supply capped']=async f=>{const {a}=await active(f);at(f,a,6,-140);await act(f,a,'collect','portal-med');assert.equal(f.me(a).health,100);};
cases['25 decision requires different explorers']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);at(f,a,0,-138);await act(f,a,'vote','return');expectError(await act(f,a,'vote','return'),'DUPLICATE_CONTRIBUTION');assert.equal(f.state(a).portal.decision,null);};
cases['26 mismatched choice safely rejected']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);at(f,a,0,-138);at(f,b,0,-138);await act(f,a,'vote','return');expectError(await act(f,b,'vote','helix'),'TEAM_CHOICE');};
cases['27 successful stable repaired reunited return']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-6,-132);await act(f,a,'repair','coils');await activate(f,a,b);await vote(f,a,b);at(f,a,0,-144);at(f,b,0,-144);await act(f,a,'cross','crossing');assert.equal(f.state(a).portal.ending.kind,'return');assert.ok(f.state(a).portal.ending.players.every(p=>p.escaped));};
cases['28 emergency surge produces costly ending']=async f=>{const {a,b}=await active(f);await charging(f,a,'surge');await activate(f,a,b);await vote(f,a,b);at(f,a,0,-144);at(f,b,0,-144);await act(f,a,'cross','crossing');assert.equal(f.state(a).portal.ending.kind,'costly');};
cases['29 HELIX pact deterministic alternative ending']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);await vote(f,a,b,'helix');at(f,a,0,-144);await act(f,a,'cross','crossing');assert.equal(f.state(a).portal.ending.kind,'helix');assert.ok(f.state(a).portal.ending.players.every(p=>!p.escaped));};
cases['30 incapacitated teammate causes partial escape']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-6,-132);await act(f,a,'repair','coils');await activate(f,a,b);await vote(f,a,b);internal(f,b).health=0;at(f,a,0,-144);await act(f,a,'cross','crossing');assert.equal(f.state(a).portal.ending.kind,'costly');assert.equal(f.state(a).portal.ending.players.find(p=>p.id===f.me(b).id).escaped,false);};
cases['31 simultaneous crossings resolve once']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);await vote(f,a,b);at(f,a,0,-144);at(f,b,0,-144);const r=await Promise.all([act(f,a,'cross','crossing'),act(f,b,'cross','crossing')]);assert.equal(r.filter(x=>x.ok).length,1);const ending=f.state(a).portal.ending;f.step(10000);assert.deepEqual(f.state(a).portal.ending,ending);};
cases['32 disconnect reconnect restores countdown identity']=async f=>{const {a,b}=await active(f);await charging(f,a);const deadline=f.state(a).portal.deadline,session=f.sessions.get(a);a.disconnect();await wait(20);const c=await f.open();assert.ok((await f.emit(c,'room:resume',{code:session.code,token:session.token})).ok);assert.equal(f.me(c).id,session.playerId);assert.equal(f.state(c).portal.deadline,deadline);assert.equal(f.state(c).players.length,2);assert.equal(f.state(b).hostId,f.me(b).id);};
cases['33 reservation expiry recalculates coil requirement']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-5,-124);await act(f,a,'stabilize','west');b.disconnect();await wait(20);f.step(1001);assert.equal(f.state(a).portal.status,'ACTIVE');assert.equal(f.state(a).portal.required,1);};
cases['34 disconnected coil does not count']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-5,-124);await act(f,a,'stabilize','west');a.disconnect();await wait(20);at(f,b,5,-124);await act(f,b,'stabilize','east');assert.equal(f.state(b).portal.status,'CHARGING');};
cases['35 incap coil contribution removed']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-5,-124);await act(f,a,'stabilize','west');internal(f,a).health=0;at(f,b,5,-124);await act(f,b,'stabilize','east');assert.equal(f.state(b).portal.status,'CHARGING');};
cases['36 room isolation and wrong room injection']=async f=>{const q=await active(f),r=await active(f);await charging(f,q.a);assert.equal(f.state(r.a).portal.status,'READY');expectError(await act(f,q.a,'repair','coils',{code:r.code}),'BAD_PAYLOAD');};
cases['37 malformed health completion payload rejected']=async f=>{const {a}=await active(f);expectError(await act(f,a,'route','stable',{health:999}),'BAD_PAYLOAD');expectError(await act(f,a,'finish','return'),'BAD_PAYLOAD');};
cases['38 reset clears all finale and survival state']=async f=>{const {a,b}=await active(f);await charging(f,a);f.step(90001);const id=f.state(a).portal.id;assert.ok((await f.emit(a,'room:reset',{epoch:1})).ok);const s=f.state(a);assert.equal(s.portal.status,'LOCKED');assert.equal(s.portal.ending,null);assert.equal(s.portal.deadline,0);assert.equal(s.portal.collected.length,0);assert.notEqual(s.portal.id,id);assert.equal(s.facility.stage,0);assert.equal(s.survival.energy,30);assert.equal(s.players[0].health,100);await f.start(a,b);f.unlock();expectError(await act(f,a,'route','stable',{eventId:id}),'STALE_EVENT');};
cases['39 completed ending freezes authoritative outcomes']=async f=>{const {a}=await active(f);await charging(f,a);f.step(90001);const s=f.state(a);expectError(await act(f,a,'collect','portal-cell'),'EVENT_RESOLVED');expectError(await f.emit(a,'player:input',{epoch:1,seq:1,x:0,z:-1}),'EVENT_RESOLVED');f.step(10000);assert.deepEqual(f.state(a).portal.ending,s.portal.ending);};
cases['40 north route collision and room limits']=async f=>{const {a}=await active(f);at(f,a,0,-110);await f.walk(a,0,-1,40);assert.ok(f.me(a).z<-114);at(f,a,8,-150);await f.walk(a,0,-1,40);assert.ok(f.me(a).z>-151.1);};
cases['41 six-player room needs only two coil operators']=async f=>{const q=await f.two();for(let i=0;i<4;i++){const c=await f.open();await f.join(c,q.code,'Extra'+i);await f.emit(c,'room:ready',{epoch:0,ready:true});}await f.start(q.a,q.b);f.unlock();room(f,q.a).facility.stage=3;f.step();await charging(f,q.a);await activate(f,q.a,q.b);assert.equal(f.state(q.a).portal.required,2);assert.equal(f.state(q.a).players.length,6);};
cases['42 reconnect during active countdown retains votes']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);at(f,a,0,-138);await act(f,a,'vote','return');const session=f.sessions.get(a),deadline=f.state(a).portal.deadline;a.disconnect();await wait(20);const c=await f.open();await f.emit(c,'room:resume',{code:session.code,token:session.token});assert.equal(f.state(c).portal.deadline,deadline);assert.equal(f.state(c).portal.votes.length,1);assert.equal(f.me(c).id,session.playerId);};
cases['43 expired reservation recalculates final vote']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);at(f,a,0,-138);await act(f,a,'vote','return');b.disconnect();await wait(20);f.step(1001);assert.equal(f.state(a).portal.decision,'return');};
cases['44 incapacitated voter cannot supply second agreement']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);at(f,a,0,-138);at(f,b,0,-138);await act(f,a,'vote','return');internal(f,a).health=0;await act(f,b,'vote','return');assert.equal(f.state(b).portal.decision,null);};
cases['45 high Alert deterministically makes return costly']=async f=>{const {a,b}=await active(f);await charging(f,a);at(f,a,-6,-132);await act(f,a,'repair','coils');await activate(f,a,b);await vote(f,a,b);room(f,a).survival.alert=40;at(f,a,0,-144);at(f,b,0,-144);await act(f,a,'cross','crossing');assert.equal(f.state(a).portal.ending.kind,'costly');};
cases['46 different rooms reach independent endings']=async f=>{const q=await active(f),r=await active(f);await charging(f,q.a);await activate(f,q.a,q.b);await vote(f,q.a,q.b,'helix');at(f,q.a,0,-144);await act(f,q.a,'cross','crossing');await charging(f,r.a);f.step(90001);assert.equal(f.state(q.a).portal.ending.kind,'helix');assert.equal(f.state(r.a).portal.ending.kind,'stranded');};
cases['47 premature crossing cannot claim an ending']=async f=>{const {a,b}=await active(f);await charging(f,a);await activate(f,a,b);at(f,a,0,-144);expectError(await act(f,a,'cross','crossing'),'BAD_PHASE');assert.equal(f.state(a).portal.ending,null);};
cases['48 final walking never spends Energy']=async f=>{const {a}=await active(f);await charging(f,a);at(f,a,-6,-118);await f.walk(a,0,-1,40);assert.equal(f.state(a).survival.energy,10);};
for(const [name,run] of Object.entries(cases))test('M5 '+name,async t=>run(await fixture(t)));
