import {chromium} from '@playwright/test';import {createTimefallApp} from '../dist-server/server/app.js';import {resolve,dirname} from 'node:path';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=resolve(process.env.BASE_URL?'evidence/m3-staging':'evidence/m3-local');await mkdir(out,{recursive:true});const runtime=process.env.BASE_URL?null:createTimefallApp();const base=process.env.BASE_URL||`http://127.0.0.1:${await runtime.listen()}`;const executablePath=process.env.CHROMIUM_PATH||resolve('../browser-runtime/chromium');const checks=[],errors=[],browsers=[],metrics={base,environment:'Two independent Chromium processes; SwiftShader software WebGL; desktop 960x640 and touch 390x844, not physical phones'};let A,B;
const launch=()=>chromium.launch({executablePath,...(process.env.BROWSER_PROXY?{proxy:{server:process.env.BROWSER_PROXY}}:{}),args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:dirname(executablePath),FONTCONFIG_PATH:resolve(dirname(executablePath),'fonts')}});
const v=p=>p.evaluate(()=>window.__M3);const wait=(p,fn,arg)=>p.waitForFunction(fn,arg,{timeout:65000});const shot=(p,n)=>p.screenshot({path:resolve(out,n+'.png')});const pass=(name,condition=true)=>{assert.ok(condition,name);checks.push({name,result:'PASS'});console.log('PASS',name)};
async function walk(p,key,axis,goal){await wait(p,()=>!document.querySelector('dialog[open]'));await p.keyboard.down(key);try{await wait(p,([axis,goal,key])=>{const me=window.__M3.network.prediction;return key==='w'||key==='a'?me[axis]<=goal:me[axis]>=goal},[axis,goal,key]);}finally{await p.keyboard.up(key);}await p.waitForTimeout(700);}
async function reset(){await A.locator('#help').click();await A.locator('#reset').click();await wait(B,()=>window.__M3.network.state.phase==='lobby');await A.locator('#readyButton').click();await B.locator('#readyButton').click();await wait(A,()=>window.__M3.network.state.players.every(p=>p.ready));await A.locator('#startGame').click();await wait(A,()=>window.__M3.started&&!window.__M3.intro);await wait(B,()=>window.__M3.started&&!window.__M3.intro);}
try{
 for(const mobile of [false,true]){const b=await launch();browsers.push(b);const c=await b.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true}:{viewport:{width:960,height:640}});const p=await c.newPage();p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});if(mobile)B=p;else A=p;}
 await A.goto(base);await wait(A,()=>window.__M3?.network.connected);await A.locator('#nickname').fill('Nova');await A.locator('#submitRoom').click();await A.locator('#lobby').waitFor({state:'visible'});const code=await A.locator('#lobbyCode').textContent();await B.goto(base);await wait(B,()=>window.__M3?.network.connected);await B.locator('#joinMode').click();await B.locator('#nickname').fill('Echo');await B.locator('#roomCode').fill(code);await B.locator('#submitRoom').click();await wait(A,()=>window.__M3.network.state.players.length===2);await A.locator('#readyButton').click();await B.locator('#readyButton').click();await wait(A,()=>window.__M3.network.state.players.every(p=>p.ready));await A.locator('#startGame').click();await wait(A,()=>window.__M3.started&&!window.__M3.intro);await wait(B,()=>window.__M3.started&&!window.__M3.intro);
 const aId=(await v(A)).network.playerId,bId=(await v(B)).network.playerId;pass('Independent players enter same authoritative 3D room',aId!==bId&&(await v(A)).network.socketId!==(await v(B)).network.socketId&&(await v(A)).remotePlayers.length===1);pass('Initial survival values synchronize',JSON.stringify((await v(A)).network.state.survival)===JSON.stringify((await v(B)).network.state.survival));
 await walk(A,'w','z',2);await wait(B,id=>window.__M3.remotePlayers.find(p=>p.id===id).z<3,aId);pass('A movement reaches B while B remains independent',(await v(B)).network.state.players.find(p=>p.id===bId).z===11);await A.locator('#interact').click();await wait(B,()=>window.__M3.network.state.survival.energy===50);await wait(A,()=>window.__M3.network.state.survival.energy===50);await wait(A,()=>document.querySelector('#energyValue').textContent==='50');await wait(B,()=>document.querySelector('#energyValue').textContent==='50');pass('Physical supply collection updates both HUDs',(await A.locator('#energyValue').textContent())==='50'&&(await B.locator('#energyValue').textContent())==='50');await A.keyboard.press('e');await A.waitForTimeout(350);pass('Repeat action cannot duplicate collected energy',(await v(A)).network.state.survival.energy===50);await shot(A,'01-collected-supply');
 await walk(A,'w','z',-5.4);await A.locator('#interact').click();await wait(B,()=>window.__M3.stage===1);await walk(A,'w','z',-10);await A.locator('#interact').click();await wait(B,()=>window.__M3.network.state.survival.resources===4);pass('Material collection synchronizes shared reserve');await walk(A,'w','z',-17);await A.locator('#interact').click();await A.locator('[data-choice="bypass"]').click();await wait(B,()=>window.__M3.network.state.survival.event.status==='active');await wait(A,()=>window.__M3.network.state.survival.event.status==='active');pass('Risky choice conserves reserves and synchronizes alert',(await v(B)).network.state.survival.alert===20&&(await v(B)).network.state.survival.energy===50);const deadline=(await v(A)).network.state.survival.event.deadline;pass('Both display the same authoritative event deadline',deadline===(await v(B)).network.state.survival.event.deadline);await A.locator('#interact').click();await wait(B,()=>window.__M3.network.state.survival.event.contributors.length===1);
 await walk(B,'w','z',-17);await B.locator('#interact').click();await wait(A,()=>window.__M3.network.state.survival.event.status==='success');pass('Separate players operate WEST and EAST before timeout',(await v(A)).network.state.survival.event.contributors.length===2);await shot(A,'02-cooperative-success-A');await shot(B,'03-cooperative-success-mobile-B');
 await walk(B,'w','z',-23);await wait(A,id=>window.__M3.network.state.players.find(p=>p.id===id).health<100,bId);pass('Server drone damage and alert synchronize');await wait(B,id=>window.__M3.network.state.players.find(p=>p.id===id).incapacitated,bId);await wait(A,id=>window.__M3.network.state.players.find(p=>p.id===id).incapacitated,bId);pass('Drone causes synchronized incapacitation',(await v(A)).network.state.players.find(p=>p.id===bId).incapacitated);await shot(B,'04-incapacitated-B');
 await walk(A,'d','x',0);await walk(A,'w','z',-21.8);await wait(A,()=>document.querySelector('#actionLabel').textContent.startsWith('Revive'));await A.locator('#interact').click();await wait(B,id=>window.__M3.network.state.players.find(p=>p.id===id).health===40,bId);pass('Nearby teammate restores Health 40 by actual revive interaction');await Promise.all([walk(B,'s','z',-18),walk(A,'s','z',-18)]);await shot(A,'05-revive-A');
 const before=(await v(B)).network.state;await B.goto('about:blank');await wait(A,id=>!window.__M3.network.state.players.find(p=>p.id===id).connected,bId);await B.goto(base);await wait(B,id=>window.__M3.network.connected&&window.__M3.network.playerId===id,bId);pass('Reconnect restores M3 event supplies health and same avatar',(await v(B)).network.state.survival.event.id===before.survival.event.id&&(await v(B)).network.state.players.length===2&&(await v(B)).network.state.players.find(p=>p.id===bId).health===before.players.find(p=>p.id===bId).health&&JSON.stringify((await v(B)).network.state.survival)===JSON.stringify(before.survival));await shot(B,'06-reconnected-B');
 await B.setViewportSize({width:844,height:390});await B.waitForTimeout(300);pass('Mobile orientation preserves joystick and HUD',await B.locator('#joystick').isVisible()&&await B.locator('#survivalHUD').isVisible());await shot(B,'07-landscape-B');await B.setViewportSize({width:390,height:844});
 await reset();pass('Reset clears health resources alert supplies and event',(await v(A)).network.state.survival.energy===30&&(await v(A)).network.state.survival.resources===2&&(await v(A)).network.state.survival.alert===0&&(await v(A)).network.state.survival.collected.length===0&&(await v(A)).network.state.players.every(p=>p.health===100));
 // Physically reach beacon and terminal again; choose bypass but deliberately withhold contributions.
 await walk(A,'w','z',-5.4); // passing supplies without collecting intentionally
 await A.locator('#interact').click();await wait(B,()=>window.__M3.stage===1);await walk(A,'w','z',-17);await walk(B,'a','x',-1.7);await walk(B,'w','z',-17);await B.locator('#interact').tap();await shot(B,'08-mobile-decisions');const buttons=await B.locator('[data-choice]').all();for(const button of buttons){const box=await button.boundingBox();assert.ok(box.width>=44&&box.height>=44);}pass('Portrait decision overlay has three usable touch targets',buttons.length===3);await B.locator('[data-choice="bypass"]').tap();await wait(B,()=>window.__M3.network.state.survival.event.status==='active');await wait(A,()=>window.__M3.network.state.survival.event.status==='timeout');await wait(B,()=>window.__M3.network.state.survival.event.status==='timeout');pass('Server timeout resolves consistently without client completion',(await v(A)).network.state.players.every(p=>p.health===70)&&(await v(B)).network.state.survival.alert===35);const revision=(await v(A)).network.state.survival.event.id;await A.waitForTimeout(1000);pass('Timeout remains resolved exactly once',(await v(A)).network.state.players.every(p=>p.health===70));await shot(A,'08-timeout-A');await shot(B,'09-timeout-mobile-B');metrics.desktop=await v(A);metrics.mobile=await v(B);pass('No serious console or runtime errors',errors.length===0);
}catch(e){checks.push({name:String(e.stack||e),result:'FAIL'});console.error(e);process.exitCode=1;if(A)await shot(A,'failure-A').catch(()=>{});if(B)await shot(B,'failure-B').catch(()=>{});}
finally{await writeFile(resolve(out,'results.json'),JSON.stringify({checks,errors,metrics},null,2));for(const b of browsers)await b.close();if(runtime)await runtime.close();console.log(`${checks.filter(c=>c.result==='PASS').length} passed; ${checks.filter(c=>c.result==='FAIL').length} failed`);}
