import {freshPortal,type PortalState,portalColliders} from '../shared/portal.js';
import {portalAction,portalTick,portalRecalculate} from './portal.js';
import {freshFacility,facilityColliders,type FacilityState} from '../shared/facility.js';
import {facilityAction,facilityTick,facilityRecalculate} from './facility.js';
import {SURVIVAL,SUPPLIES,SECURITY,TERMINALS,freshSurvival,type SurvivalState,type Choice} from '../shared/survival.js';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {move} from '../shared/collision.js';
import {COLLIDERS,COLORS,SPEED,TICK_MS,ARRIVAL_MS,spawnPosition} from '../shared/world-map.js';
import {CODE_ALPHABET,type RoomState,type InputCommand,type Action,type Session,type SurvivalAction,type FacilityAction,type PortalAction} from '../shared/protocol.js';
export class RuleError extends Error{constructor(public code:string){super(code);}}
const requireRule=(test:unknown,code:string)=>{if(!test)throw new RuleError(code);};
type Player={id:string;nickname:string;color:string;slot:number;socketId:string|null;ready:boolean;x:number;z:number;angle:number;appliedSeq:number;lastSeq:number;queue:InputCommand[];lastInputAt:number;disconnectedAt:number|null;tokenHash:string;health:number;nextDamageAt:number;nextFacilityDamageAt?:number;nextPortalDamageAt?:number;requests:Set<string>};
type Room={code:string;epoch:number;revision:number;phase:'lobby'|'playing';hostId:string|null;startedAt:number;objective:{stage:number;version:number};survival:SurvivalState;facility:FacilityState;portal:PortalState;facilitySecret:number;players:Map<string,Player>};
export type Notice={code:string;kind:string;text:string};
export class RoomManager{
 readonly rooms=new Map<string,Room>();readonly sockets=new Map<string,{code:string;id:string}>();readonly sessions=new Map<string,{code:string;id:string}>();
 constructor(public graceMs=90_000,private clock=Date.now,private notify:(n:Notice)=>void=()=>{},private changed:(code:string)=>void=()=>{}){}
 private hash(token:string){return createHash('sha256').update(token).digest('hex');}
 private room(code:string){const room=this.rooms.get(code);requireRule(room,'ROOM_NOT_FOUND');return room!;}
 private member(socketId:string){const m=this.sockets.get(socketId);requireRule(m,'NOT_JOINED');const room=this.room(m!.code),player=room.players.get(m!.id);requireRule(player?.socketId===socketId,'NOT_JOINED');return {room,player:player!};}
 private update(room:Room,kind?:string,text?:string){room.revision++;this.changed(room.code);if(kind)this.notify({code:room.code,kind,text:text!});}
 private checkEpoch(room:Room,epoch:number){requireRule(epoch===room.epoch,'STALE_EPOCH');}
 create(socketId:string,nickname:string){requireRule(!this.sockets.has(socketId),'ALREADY_JOINED');requireRule(this.rooms.size<300,'SERVER_FULL');let code='';do{code=Array.from({length:5},()=>CODE_ALPHABET[randomBytes(1)[0]%CODE_ALPHABET.length]).join('');}while(this.rooms.has(code));const room:Room={code,epoch:0,revision:0,phase:'lobby',hostId:null,startedAt:0,objective:{stage:0,version:0},survival:freshSurvival(),facility:freshFacility(randomUUID()),portal:freshPortal(randomUUID()),facilitySecret:randomBytes(1)[0]%3,players:new Map()};this.rooms.set(code,room);return this.add(room,socketId,nickname);}
 join(socketId:string,code:string,nickname:string){requireRule(!this.sockets.has(socketId),'ALREADY_JOINED');const room=this.room(code);requireRule(room.phase==='lobby','ROOM_STARTED');requireRule(room.players.size<6,'ROOM_FULL');return this.add(room,socketId,nickname);}
 private add(room:Room,socketId:string,nickname:string):Session{const slot=COLORS.findIndex((_,i)=>![...room.players.values()].some(p=>p.slot===i));const id=randomUUID(),token=randomBytes(32).toString('base64url'),tokenHash=this.hash(token);const player:Player={id,nickname,color:COLORS[slot],slot,socketId,ready:false,...spawnPosition(slot),angle:0,appliedSeq:0,lastSeq:0,queue:[],lastInputAt:this.clock(),disconnectedAt:null,tokenHash,health:SURVIVAL.health,nextDamageAt:0,requests:new Set()};room.players.set(id,player);this.sockets.set(socketId,{code:room.code,id});this.sessions.set(tokenHash,{code:room.code,id});if(!room.hostId)room.hostId=id;this.update(room,'joined',`${nickname} joined the expedition.`);return {code:room.code,playerId:id,token};}
 resume(socketId:string,code:string,token:string):Session{requireRule(!this.sockets.has(socketId),'ALREADY_JOINED');const record=this.sessions.get(this.hash(token));requireRule(record&&record.code===code,'INVALID_SESSION');const room=this.rooms.get(code),player=room?.players.get(record!.id);requireRule(room&&player,'INVALID_SESSION');requireRule(!player!.socketId,'SESSION_ACTIVE');requireRule(player!.disconnectedAt!==null&&this.clock()-player!.disconnectedAt<this.graceMs,'INVALID_SESSION');player!.socketId=socketId;player!.disconnectedAt=null;player!.queue=[];this.sockets.set(socketId,record!);if(!room!.hostId)room!.hostId=player!.id;this.update(room!,'reconnected',`${player!.nickname} reconnected.`);return {code,playerId:player!.id,token};}
 ready(socketId:string,ready:boolean,epoch:number){const {room,player}=this.member(socketId);this.checkEpoch(room,epoch);requireRule(room.phase==='lobby','BAD_PHASE');player.ready=ready;this.update(room);}
 start(socketId:string,epoch:number){const {room,player}=this.member(socketId);this.checkEpoch(room,epoch);requireRule(room.hostId===player.id,'NOT_HOST');requireRule(room.phase==='lobby','BAD_PHASE');const connected=[...room.players.values()].filter(p=>p.socketId);requireRule(connected.length>=2,'TOO_FEW_PLAYERS');requireRule(connected.every(p=>p.ready),'NOT_READY');room.epoch++;room.phase='playing';room.startedAt=this.clock();room.objective={stage:0,version:0};room.survival=freshSurvival();room.facility=freshFacility(randomUUID());room.portal=freshPortal(randomUUID());room.facilitySecret=randomBytes(1)[0]%3;for(const p of room.players.values()){Object.assign(p,spawnPosition(p.slot));p.angle=0;p.lastSeq=p.appliedSeq=0;p.queue=[];p.requests.clear();p.health=SURVIVAL.health;p.nextDamageAt=0;p.nextFacilityDamageAt=0;p.nextPortalDamageAt=0;}this.update(room,'started','Expedition started. Welcome to 2126.');}
 input(socketId:string,input:InputCommand){const {room,player}=this.member(socketId);this.checkEpoch(room,input.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(room.portal.status!=='RESOLVED','EVENT_RESOLVED');requireRule(player.health>0,'INCAPACITATED');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');requireRule(input.seq>player.lastSeq&&input.seq<=player.lastSeq+1000,'STALE_INPUT');player.lastSeq=input.seq;player.lastInputAt=this.clock();player.queue.push(input);if(player.queue.length>4)player.queue.shift();return input.seq;}
 interact(socketId:string,action:Action){const {room,player}=this.member(socketId);this.checkEpoch(room,action.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(room.portal.status!=='RESOLVED','EVENT_RESOLVED');requireRule(player.health>0,'INCAPACITATED');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');requireRule(!player.requests.has(action.requestId),'DUPLICATE_ACTION');requireRule(action.objectiveVersion===room.objective.version,'STALE_OBJECTIVE');requireRule((room.objective.stage===0&&action.target==='beacon')||(room.objective.stage===1&&action.target==='signal'),'STALE_OBJECTIVE');const target=action.target==='beacon'?{x:0,z:-7,r:2.8}:{x:0,z:-38,r:4};requireRule(Math.hypot(player.x-target.x,player.z-target.z)<target.r,'OUT_OF_RANGE');player.requests.add(action.requestId);if(player.requests.size>64)player.requests.delete(player.requests.values().next().value!);room.objective.stage++;room.objective.version++;this.update(room,'objective',action.target==='beacon'?`${player.nickname} restored the beacon. Follow the portal signal north.`:`${player.nickname} confirmed the portal signal. Team survey complete.`);}
 private damage(player:Player,amount:number){player.health=Math.max(0,Math.min(SURVIVAL.health,player.health-amount));if(!player.health)player.queue=[];}
 private near(player:Player,target:{x:number;z:number},range:number){requireRule(Math.hypot(player.x-target.x,player.z-target.z)<range,'OUT_OF_RANGE');}
 private recalculate(room:Room){const e=room.survival.event;e.required=Math.min(2,room.players.size);e.contributors=e.contributors.filter(c=>room.players.has(c.playerId));if(e.status==='active'&&e.contributors.length>=e.required&&e.required>0)this.finish(room,false);}
 private finish(room:Room,timeout:boolean){const s=room.survival,e=s.event;if(e.status!=='active')return;e.status=timeout?'timeout':'success';if(timeout){s.alert=Math.min(100,s.alert+SURVIVAL.timeoutAlert);s.security='active';for(const p of room.players.values())this.damage(p,SURVIVAL.timeoutDamage);e.result='Security rebooted. Team shock damage; alert increased.';}else{e.result=s.security==='disabled'?'Two operators disabled the drone. Safe passage.':s.security==='shielded'?'Team shielding is online. Security damage reduced.':'Risky bypass established. The drone remains dangerous.';}this.update(room,'survival',e.result);}
 private survivalTick(room:Room,now:number){if(room.phase!=='playing'||now<room.startedAt+ARRIVAL_MS)return;const s=room.survival;if(s.event.status==='active'&&now>=s.event.deadline)this.finish(room,true);if(room.objective.stage<1||s.security==='disabled')return;let changed=false;for(const p of room.players.values()){if(!p.socketId||p.health<=0||now<p.nextDamageAt||Math.hypot(p.x-SECURITY.x,p.z-SECURITY.z)>=SECURITY.radius)continue;p.nextDamageAt=now+SURVIVAL.damageIntervalMs;this.damage(p,s.security==='shielded'?5:s.security==='aggressive'?35:SURVIVAL.hazardDamage);s.alert=Math.min(100,s.alert+SURVIVAL.alertPerDetection);changed=true;}if(changed)this.update(room,'hazard','Drone detected an explorer. Leave the red zone or secure the terminals.');}
 survivalAction(socketId:string,action:SurvivalAction){const {room,player}=this.member(socketId);this.checkEpoch(room,action.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(room.portal.status!=='RESOLVED','EVENT_RESOLVED');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');requireRule(player.health>0,'INCAPACITATED');requireRule(!player.requests.has(action.requestId),'DUPLICATE_ACTION');const s=room.survival,e=s.event;requireRule(action.eventId===e.id,'STALE_EVENT');
 if(action.kind==='collect'){const item=SUPPLIES.find(i=>i.id===action.target);requireRule(item,'INVALID_TARGET');this.near(player,item!,SURVIVAL.collectRange);requireRule(!s.collected.includes(item!.id),'ALREADY_COLLECTED');s.collected.push(item!.id);if(item!.kind==='energy')s.energy=Math.min(100,s.energy+item!.amount);else if(item!.kind==='resources')s.resources=Math.min(20,s.resources+item!.amount);else player.health=Math.min(SURVIVAL.health,player.health+item!.amount);}
 else if(action.kind==='revive'){const other=room.players.get(action.target);requireRule(other&&other.id!==player.id&&other.socketId,'INVALID_TARGET');this.near(player,other!,SURVIVAL.reviveRange);requireRule(other!.health===0,'ALREADY_REVIVED');other!.health=SURVIVAL.reviveHealth;other!.nextDamageAt=this.clock()+SURVIVAL.damageIntervalMs;}
 else {requireRule(room.objective.stage>=1,'NEED_BEACON');if(e.status==='active'&&this.clock()>=e.deadline){this.finish(room,true);throw new RuleError('EVENT_RESOLVED');}if(action.kind==='choose'){this.near(player,TERMINALS.prime,SURVIVAL.terminalRange);requireRule(e.status==='idle','EVENT_RESOLVED');requireRule(['energy','repair','bypass'].includes(action.target),'INVALID_TARGET');const choice=action.target as Choice;requireRule(choice!=='energy'||s.energy>=SURVIVAL.energyCost,'INSUFFICIENT_SUPPLIES');requireRule(choice!=='repair'||s.resources>=SURVIVAL.repairCost,'INSUFFICIENT_SUPPLIES');if(choice==='energy')s.energy-=SURVIVAL.energyCost;if(choice==='repair')s.resources-=SURVIVAL.repairCost;if(choice==='bypass')s.alert=Math.min(100,s.alert+20);s.security=choice==='energy'?'disabled':choice==='repair'?'shielded':'aggressive';e.id=randomUUID();e.status='active';e.choice=choice;e.deadline=this.clock()+SURVIVAL.eventMs;e.required=Math.min(2,room.players.size);e.result='Power the west terminal and ground the east terminal. Different explorers must operate them.';}
 else {requireRule(e.status==='active','EVENT_RESOLVED');requireRule(action.target==='prime'||action.target==='ground','INVALID_TARGET');const role=action.target as 'prime'|'ground';this.near(player,TERMINALS[role],SURVIVAL.terminalRange);requireRule(!e.contributors.some(c=>c.playerId===player.id),'DUPLICATE_CONTRIBUTION');requireRule(!e.contributors.some(c=>c.role===role),'ROLE_TAKEN');e.contributors.push({playerId:player.id,role});if(e.contributors.length>=e.required)this.finish(room,false);}}
 player.requests.add(action.requestId);if(player.requests.size>64)player.requests.delete(player.requests.values().next().value!);this.update(room,'survival',action.kind==='collect'?`${player.nickname} collected a supply.`:action.kind==='revive'?`${player.nickname} revived a teammate.`:e.result);
 }
 facilityAction(socketId:string,action:FacilityAction){const {room,player}=this.member(socketId);this.checkEpoch(room,action.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(room.portal.status!=='RESOLVED','EVENT_RESOLVED');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');requireRule(player.health>0,'INCAPACITATED');facilityAction(room,player,action,this.clock(),requireRule);this.update(room,'facility',room.facility.result);}
 portalAction(socketId:string,action:PortalAction){const {room,player}=this.member(socketId);this.checkEpoch(room,action.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(player.health>0,'INCAPACITATED');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');try{portalAction(room,player,action,this.clock(),requireRule);}finally{this.update(room,'portal',room.portal.result);}}
 reset(socketId:string,epoch:number){const {room,player}=this.member(socketId);this.checkEpoch(room,epoch);requireRule(room.hostId===player.id,'NOT_HOST');requireRule(room.phase==='playing','BAD_PHASE');room.epoch++;room.phase='lobby';room.startedAt=0;room.objective={stage:0,version:0};room.survival=freshSurvival();room.facility=freshFacility(randomUUID());room.portal=freshPortal(randomUUID());room.facilitySecret=randomBytes(1)[0]%3;for(const p of room.players.values()){p.ready=false;p.queue=[];p.appliedSeq=p.lastSeq=0;p.requests.clear();p.health=SURVIVAL.health;p.nextDamageAt=0;p.nextFacilityDamageAt=0;p.nextPortalDamageAt=0;p.angle=0;Object.assign(p,spawnPosition(p.slot));}this.update(room,'reset','Back in the lobby. Ready up for another survey.');}
 disconnect(socketId:string){const m=this.sockets.get(socketId);if(!m)return;this.sockets.delete(socketId);const room=this.rooms.get(m.code),player=room?.players.get(m.id);if(!room||!player||player.socketId!==socketId)return;player.socketId=null;player.disconnectedAt=this.clock();player.queue=[];player.ready=false;this.transfer(room);this.update(room,'disconnected',`${player.nickname} disconnected. Their place is reserved temporarily.`);}
 leave(socketId:string){const {room,player}=this.member(socketId);this.sockets.delete(socketId);this.remove(room,player);}
 private transfer(room:Room){if(room.hostId&&room.players.get(room.hostId)?.socketId)return;const old=room.hostId;room.hostId=[...room.players.values()].find(p=>p.socketId)?.id??null;if(old!==room.hostId&&room.hostId)this.notify({code:room.code,kind:'host',text:`${room.players.get(room.hostId)!.nickname} is now the host.`});}
 private remove(room:Room,player:Player){this.sessions.delete(player.tokenHash);room.players.delete(player.id);if(!room.players.size){this.rooms.delete(room.code);return;}this.transfer(room);this.recalculate(room);facilityRecalculate(room);portalRecalculate(room,this.clock());this.update(room,'left',`${player.nickname} left the expedition.`);}
 tick(){const now=this.clock();for(const room of [...this.rooms.values()]){if(room.portal.status!=='RESOLVED')this.survivalTick(room,now);if(room.phase==='playing'&&portalTick(room,now))this.update(room,'portal',room.portal.result);if(room.phase==='playing'&&room.portal.status!=='RESOLVED'&&facilityTick(room,now))this.update(room,'facility','Facility security changed. Avoid the red fields.');for(const p of [...room.players.values()]){if(!p.socketId&&p.disconnectedAt!==null&&now-p.disconnectedAt>=this.graceMs){this.remove(room,p);continue;}if(room.phase!=='playing'||room.portal.status==='RESOLVED'||p.health<=0||!p.socketId||now<room.startedAt+ARRIVAL_MS)continue;if(now-p.lastInputAt>250){p.queue=[];continue;}const command=p.queue.shift();if(!command)continue;const position=move(p,command.x*SPEED*TICK_MS/1000,command.z*SPEED*TICK_MS/1000,[...COLLIDERS,...portalColliders(),...facilityColliders(room.facility,room.objective.stage,['success','timeout'].includes(room.survival.event.status))]);p.x=position.x;p.z=position.z;p.appliedSeq=command.seq;if(Math.hypot(command.x,command.z)>.05)p.angle=Math.atan2(-command.x,-command.z);} }}
 state(code:string):RoomState{const room=this.room(code);return {code:room.code,epoch:room.epoch,revision:room.revision,phase:room.phase,hostId:room.hostId,serverTime:this.clock(),startedAt:room.startedAt,arrivalEndsAt:room.startedAt?room.startedAt+ARRIVAL_MS:0,objective:{...room.objective},survival:structuredClone(room.survival),facility:structuredClone(room.facility),portal:structuredClone(room.portal),players:[...room.players.values()].map(p=>({id:p.id,nickname:p.nickname,color:p.color,connected:Boolean(p.socketId),ready:p.ready,x:p.x,z:p.z,angle:p.angle,appliedSeq:p.appliedSeq,lastSeq:p.lastSeq,health:p.health,incapacitated:p.health===0}))};}
 membership(socketId:string){return this.sockets.get(socketId);}
}
