import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {move} from '../shared/collision.js';
import {COLLIDERS,COLORS,SPEED,TICK_MS,ARRIVAL_MS,spawnPosition} from '../shared/world-map.js';
import {CODE_ALPHABET,type RoomState,type InputCommand,type Action,type Session} from '../shared/protocol.js';
export class RuleError extends Error{constructor(public code:string){super(code);}}
const requireRule=(test:unknown,code:string)=>{if(!test)throw new RuleError(code);};
type Player={id:string;nickname:string;color:string;slot:number;socketId:string|null;ready:boolean;x:number;z:number;angle:number;appliedSeq:number;lastSeq:number;queue:InputCommand[];lastInputAt:number;disconnectedAt:number|null;tokenHash:string;requests:Set<string>};
type Room={code:string;epoch:number;revision:number;phase:'lobby'|'playing';hostId:string|null;startedAt:number;objective:{stage:number;version:number};players:Map<string,Player>};
export type Notice={code:string;kind:string;text:string};
export class RoomManager{
 readonly rooms=new Map<string,Room>();readonly sockets=new Map<string,{code:string;id:string}>();readonly sessions=new Map<string,{code:string;id:string}>();
 constructor(public graceMs=90_000,private clock=Date.now,private notify:(n:Notice)=>void=()=>{},private changed:(code:string)=>void=()=>{}){}
 private hash(token:string){return createHash('sha256').update(token).digest('hex');}
 private room(code:string){const room=this.rooms.get(code);requireRule(room,'ROOM_NOT_FOUND');return room!;}
 private member(socketId:string){const m=this.sockets.get(socketId);requireRule(m,'NOT_JOINED');const room=this.room(m!.code),player=room.players.get(m!.id);requireRule(player?.socketId===socketId,'NOT_JOINED');return {room,player:player!};}
 private update(room:Room,kind?:string,text?:string){room.revision++;this.changed(room.code);if(kind)this.notify({code:room.code,kind,text:text!});}
 private checkEpoch(room:Room,epoch:number){requireRule(epoch===room.epoch,'STALE_EPOCH');}
 create(socketId:string,nickname:string){requireRule(!this.sockets.has(socketId),'ALREADY_JOINED');requireRule(this.rooms.size<300,'SERVER_FULL');let code='';do{code=Array.from({length:5},()=>CODE_ALPHABET[randomBytes(1)[0]%CODE_ALPHABET.length]).join('');}while(this.rooms.has(code));const room:Room={code,epoch:0,revision:0,phase:'lobby',hostId:null,startedAt:0,objective:{stage:0,version:0},players:new Map()};this.rooms.set(code,room);return this.add(room,socketId,nickname);}
 join(socketId:string,code:string,nickname:string){requireRule(!this.sockets.has(socketId),'ALREADY_JOINED');const room=this.room(code);requireRule(room.phase==='lobby','ROOM_STARTED');requireRule(room.players.size<6,'ROOM_FULL');return this.add(room,socketId,nickname);}
 private add(room:Room,socketId:string,nickname:string):Session{const slot=COLORS.findIndex((_,i)=>![...room.players.values()].some(p=>p.slot===i));const id=randomUUID(),token=randomBytes(32).toString('base64url'),tokenHash=this.hash(token);const player:Player={id,nickname,color:COLORS[slot],slot,socketId,ready:false,...spawnPosition(slot),angle:0,appliedSeq:0,lastSeq:0,queue:[],lastInputAt:this.clock(),disconnectedAt:null,tokenHash,requests:new Set()};room.players.set(id,player);this.sockets.set(socketId,{code:room.code,id});this.sessions.set(tokenHash,{code:room.code,id});if(!room.hostId)room.hostId=id;this.update(room,'joined',`${nickname} joined the expedition.`);return {code:room.code,playerId:id,token};}
 resume(socketId:string,code:string,token:string):Session{requireRule(!this.sockets.has(socketId),'ALREADY_JOINED');const record=this.sessions.get(this.hash(token));requireRule(record&&record.code===code,'INVALID_SESSION');const room=this.rooms.get(code),player=room?.players.get(record!.id);requireRule(room&&player,'INVALID_SESSION');requireRule(!player!.socketId,'SESSION_ACTIVE');requireRule(player!.disconnectedAt!==null&&this.clock()-player!.disconnectedAt<this.graceMs,'INVALID_SESSION');player!.socketId=socketId;player!.disconnectedAt=null;player!.queue=[];this.sockets.set(socketId,record!);if(!room!.hostId)room!.hostId=player!.id;this.update(room!,'reconnected',`${player!.nickname} reconnected.`);return {code,playerId:player!.id,token};}
 ready(socketId:string,ready:boolean,epoch:number){const {room,player}=this.member(socketId);this.checkEpoch(room,epoch);requireRule(room.phase==='lobby','BAD_PHASE');player.ready=ready;this.update(room);}
 start(socketId:string,epoch:number){const {room,player}=this.member(socketId);this.checkEpoch(room,epoch);requireRule(room.hostId===player.id,'NOT_HOST');requireRule(room.phase==='lobby','BAD_PHASE');const connected=[...room.players.values()].filter(p=>p.socketId);requireRule(connected.length>=2,'TOO_FEW_PLAYERS');requireRule(connected.every(p=>p.ready),'NOT_READY');room.epoch++;room.phase='playing';room.startedAt=this.clock();room.objective={stage:0,version:0};for(const p of room.players.values()){Object.assign(p,spawnPosition(p.slot));p.angle=0;p.lastSeq=p.appliedSeq=0;p.queue=[];p.requests.clear();}this.update(room,'started','Expedition started. Welcome to 2126.');}
 input(socketId:string,input:InputCommand){const {room,player}=this.member(socketId);this.checkEpoch(room,input.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');requireRule(input.seq>player.lastSeq&&input.seq<=player.lastSeq+1000,'STALE_INPUT');player.lastSeq=input.seq;player.lastInputAt=this.clock();player.queue.push(input);if(player.queue.length>4)player.queue.shift();return input.seq;}
 interact(socketId:string,action:Action){const {room,player}=this.member(socketId);this.checkEpoch(room,action.epoch);requireRule(room.phase==='playing','BAD_PHASE');requireRule(this.clock()>=room.startedAt+ARRIVAL_MS,'ARRIVING');requireRule(!player.requests.has(action.requestId),'DUPLICATE_ACTION');requireRule(action.objectiveVersion===room.objective.version,'STALE_OBJECTIVE');requireRule((room.objective.stage===0&&action.target==='beacon')||(room.objective.stage===1&&action.target==='signal'),'STALE_OBJECTIVE');const target=action.target==='beacon'?{x:0,z:-7,r:2.8}:{x:0,z:-38,r:4};requireRule(Math.hypot(player.x-target.x,player.z-target.z)<target.r,'OUT_OF_RANGE');player.requests.add(action.requestId);if(player.requests.size>64)player.requests.delete(player.requests.values().next().value!);room.objective.stage++;room.objective.version++;this.update(room,'objective',action.target==='beacon'?`${player.nickname} restored the beacon. Follow the portal signal north.`:`${player.nickname} confirmed the portal signal. Team survey complete.`);}
 reset(socketId:string,epoch:number){const {room,player}=this.member(socketId);this.checkEpoch(room,epoch);requireRule(room.hostId===player.id,'NOT_HOST');requireRule(room.phase==='playing','BAD_PHASE');room.epoch++;room.phase='lobby';room.startedAt=0;room.objective={stage:0,version:0};for(const p of room.players.values()){p.ready=false;p.queue=[];p.appliedSeq=p.lastSeq=0;p.requests.clear();p.angle=0;Object.assign(p,spawnPosition(p.slot));}this.update(room,'reset','Back in the lobby. Ready up for another survey.');}
 disconnect(socketId:string){const m=this.sockets.get(socketId);if(!m)return;this.sockets.delete(socketId);const room=this.rooms.get(m.code),player=room?.players.get(m.id);if(!room||!player||player.socketId!==socketId)return;player.socketId=null;player.disconnectedAt=this.clock();player.queue=[];player.ready=false;this.transfer(room);this.update(room,'disconnected',`${player.nickname} disconnected. Their place is reserved temporarily.`);}
 leave(socketId:string){const {room,player}=this.member(socketId);this.sockets.delete(socketId);this.remove(room,player);}
 private transfer(room:Room){if(room.hostId&&room.players.get(room.hostId)?.socketId)return;const old=room.hostId;room.hostId=[...room.players.values()].find(p=>p.socketId)?.id??null;if(old!==room.hostId&&room.hostId)this.notify({code:room.code,kind:'host',text:`${room.players.get(room.hostId)!.nickname} is now the host.`});}
 private remove(room:Room,player:Player){this.sessions.delete(player.tokenHash);room.players.delete(player.id);if(!room.players.size){this.rooms.delete(room.code);return;}this.transfer(room);this.update(room,'left',`${player.nickname} left the expedition.`);}
 tick(){const now=this.clock();for(const room of [...this.rooms.values()]){for(const p of [...room.players.values()]){if(!p.socketId&&p.disconnectedAt!==null&&now-p.disconnectedAt>=this.graceMs){this.remove(room,p);continue;}if(room.phase!=='playing'||!p.socketId||now<room.startedAt+ARRIVAL_MS)continue;if(now-p.lastInputAt>250){p.queue=[];continue;}const command=p.queue.shift();if(!command)continue;const position=move(p,command.x*SPEED*TICK_MS/1000,command.z*SPEED*TICK_MS/1000,COLLIDERS);p.x=position.x;p.z=position.z;p.appliedSeq=command.seq;if(Math.hypot(command.x,command.z)>.05)p.angle=Math.atan2(-command.x,-command.z);} }}
 state(code:string):RoomState{const room=this.room(code);return {code:room.code,epoch:room.epoch,revision:room.revision,phase:room.phase,hostId:room.hostId,serverTime:this.clock(),startedAt:room.startedAt,arrivalEndsAt:room.startedAt?room.startedAt+ARRIVAL_MS:0,objective:{...room.objective},players:[...room.players.values()].map(p=>({id:p.id,nickname:p.nickname,color:p.color,connected:Boolean(p.socketId),ready:p.ready,x:p.x,z:p.z,angle:p.angle,appliedSeq:p.appliedSeq,lastSeq:p.lastSeq}))};}
 membership(socketId:string){return this.sockets.get(socketId);}
}
