import {randomUUID} from 'node:crypto';
import {FACILITY,STATIONS,CACHES,GLYPHS,requiredOperators,type FacilityState} from '../shared/facility.js';
import type {FacilityAction} from '../shared/protocol.js';
type P={id:string;nickname:string;x:number;z:number;health:number;socketId:string|null;requests:Set<string>;queue:unknown[];nextFacilityDamageAt?:number};
type R={objective:{stage:number};survival:{energy:number;resources:number;alert:number;event:{status:string}};players:Map<string,P>;facility:FacilityState;facilitySecret:number};
export function facilityAction(room:R,p:P,a:FacilityAction,now:number,fail:(ok:unknown,code:string)=>void){const f=room.facility,s=room.survival;
 fail(a.eventId===f.id,'STALE_EVENT');fail(!p.requests.has(a.requestId),'DUPLICATE_ACTION');fail(room.objective.stage>=2&&['success','timeout'].includes(s.event.status),'FACILITY_LOCKED');
 const near=(target:{x:number;z:number})=>fail(Math.hypot(p.x-target.x,p.z-target.z)<FACILITY.range,'OUT_OF_RANGE');
 const spend=(energy:number,materials:number)=>{fail(s.energy>=energy&&s.resources>=materials,'INSUFFICIENT_SUPPLIES');s.energy-=energy;s.resources-=materials;};
 const damage=(amount:number)=>{p.health=Math.max(0,p.health-amount);if(!p.health)p.queue=[];};
 if(a.kind==='sync'){fail(f.stage===0,'EVENT_RESOLVED');fail(a.target==='west'||a.target==='east','INVALID_TARGET');near(STATIONS[a.target as 'west'|'east']);f.sync=f.sync.filter(c=>c.until>now&&room.players.get(c.playerId)?.socketId&&room.players.get(c.playerId)!.health>0&&Math.hypot(room.players.get(c.playerId)!.x-STATIONS[c.station as 'west'|'east'].x,room.players.get(c.playerId)!.z+42)<FACILITY.range);fail(!f.sync.some(c=>c.playerId===p.id),'DUPLICATE_CONTRIBUTION');fail(!f.sync.some(c=>c.station===a.target),'ROLE_TAKEN');f.sync.push({playerId:p.id,station:a.target,until:now+FACILITY.syncMs});if(f.sync.length>=requiredOperators(room.players.size)){f.stage=1;f.sync=[];f.result='Airlock synchronized. Enter the HELIX facility; find both archive clues.';}}
 else if(a.kind==='read'){fail(f.stage===1,'BAD_PHASE');fail(a.target==='alpha'||a.target==='beta','INVALID_TARGET');near(STATIONS[a.target as 'alpha'|'beta']);fail(!f.observations.some(c=>c.channel===a.target),'ROLE_TAKEN');fail(!f.observations.some(c=>c.playerId===p.id)&&room.players.size>1||room.players.size===1,'DUPLICATE_CONTRIBUTION');const index=a.target==='alpha'?room.facilitySecret:(room.facilitySecret+1)%3;f.observations.push({playerId:p.id,channel:a.target,glyph:GLYPHS[index]});f.result='Clue recovered. Tell your teammate the symbol; ALPHA comes before BETA.';}
 else if(a.kind==='solve'){fail(f.stage===1,'BAD_PHASE');near(STATIONS.cipher);fail(f.observations.length===2,'NEED_TEAMMATE');fail(/^(SOL|LUNA|NOVA)-(SOL|LUNA|NOVA)$/.test(a.target),'INVALID_TARGET');const answer=GLYPHS[room.facilitySecret]+'-'+GLYPHS[(room.facilitySecret+1)%3];if(a.target!==answer){s.alert=Math.min(100,s.alert+5);damage(8);f.result='Cipher rejected. +5 Alert and 8 operator damage. Combine ALPHA then BETA.';}else{f.stage=2;f.result='Cipher accepted. Research wing unlocked. Route reactor power.';}}
 else if(a.kind==='route'){fail(f.stage===2&&!f.routing,'EVENT_RESOLVED');near(STATIONS.route);fail(['energy','materials','overload'].includes(a.target),'INVALID_TARGET');if(a.target==='energy')spend(FACILITY.energyCost,0);if(a.target==='materials')spend(0,FACILITY.materialCost);if(a.target==='overload'){s.alert=Math.min(100,s.alert+15);for(const other of room.players.values()){other.health=Math.max(0,other.health-15);if(!other.health)other.queue=[];}}f.routing=a.target;f.result='Route selected. Two explorers operate GENERATOR and RELAY separately.';}
 else if(a.kind==='power'){f.contributions=f.contributions.filter(c=>(room.players.get(c.playerId)?.health??0)>0);fail(f.stage===2&&f.routing,'BAD_PHASE');fail(a.target==='generator'||a.target==='relay','INVALID_TARGET');near(STATIONS[a.target as 'generator'|'relay']);fail(!f.contributions.some(c=>c.playerId===p.id),'DUPLICATE_CONTRIBUTION');fail(!f.contributions.some(c=>c.station===a.target),'ROLE_TAKEN');f.contributions.push({playerId:p.id,station:a.target});if(f.contributions.length>=requiredOperators(room.players.size)){f.stage=3;f.result='Reactor routed. Transit checkpoint open. The portal challenge lies ahead.';}}
 else if(a.kind==='collect'){fail(f.stage>=1,'BAD_PHASE');const item=CACHES.find(i=>i.id===a.target);fail(item,'INVALID_TARGET');near(item!);fail(!f.collected.includes(a.target),'ALREADY_COLLECTED');f.collected.push(a.target);if(item!.kind==='energy')s.energy=Math.min(100,s.energy+item!.amount);else if(item!.kind==='resources')s.resources=Math.min(20,s.resources+item!.amount);else p.health=Math.min(100,p.health+item!.amount);f.result='Facility cache recovered for the team.';}
 else if(a.kind==='scanner'){fail(f.stage>=1,'BAD_PHASE');near(STATIONS.scanner);fail(f.scanner==='active','EVENT_RESOLVED');fail(['distract','disable'].includes(a.target),'INVALID_TARGET');if(a.target==='disable'){spend(0,2);f.scanner='disabled';}else{fail(now>=f.scannerUntil,'EVENT_RESOLVED');spend(8,0);f.scannerUntil=now+20_000;}f.result=a.target==='disable'?'Scanner permanently disabled.':'Scanner distracted for 20 seconds. Cross now or use the sides.';}
 else if(a.kind==='patrol'){fail(f.stage>=2,'BAD_PHASE');near(STATIONS.patrol);fail(f.patrol==='active','EVENT_RESOLVED');fail(['divert','risk'].includes(a.target),'INVALID_TARGET');if(a.target==='divert'){spend(10,0);f.patrol='diverted';}else{f.patrol='aggressive';s.alert=Math.min(100,s.alert+5);}f.result=a.target==='divert'?'Patrol diverted. The reactor approach is safer.':'Patrol challenged. +5 Alert; avoid its moving red field.';}
 else {fail(a.kind==='archive'&&a.target==='archive','INVALID_TARGET');fail(f.stage>=3,'BAD_PHASE');near(STATIONS.archive);fail(!f.archive,'ALREADY_COLLECTED');f.archive=true;s.energy=Math.min(100,s.energy+8);f.result='Optional archive: portal needs stable power and a reunited team. +8 Energy.';}
 p.requests.add(a.requestId);if(p.requests.size>64)p.requests.delete(p.requests.values().next().value!);
}
export function facilityTick(room:R,now:number){const f=room.facility;let changed=false;const previous=f.contributions.length;f.contributions=f.contributions.filter(c=>(room.players.get(c.playerId)?.health??0)>0);if(previous!==f.contributions.length)changed=true;
 if(f.stage===0){const old=f.sync.length;f.sync=f.sync.filter(c=>{const p=room.players.get(c.playerId),t=STATIONS[c.station as 'west'|'east'];return c.until>now&&p?.socketId&&p.health>0&&Math.hypot(p.x-t.x,p.z-t.z)<FACILITY.range;});changed=old!==f.sync.length;if(f.sync.length>=requiredOperators(room.players.size)&&f.sync.length>0&&room.objective.stage>=2&&['success','timeout'].includes(room.survival.event.status)){f.stage=1;f.sync=[];f.result='Remaining operator opened the airlock after reservation expiry.';changed=true;}}
 if(f.stage<1)return changed;
 for(const p of room.players.values()){if(!p.socketId||p.health<=0||now<(p.nextFacilityDamageAt??0))continue;const scanner=f.scanner==='active'&&now>=f.scannerUntil&&Math.hypot(p.x,p.z+60)<3.2;const patrol=f.stage>=2&&f.patrol!=='diverted'&&Math.hypot(p.x-Math.sin(now/1800)*4,p.z+86)<2.2;if(!scanner&&!patrol)continue;p.health=Math.max(0,p.health-(scanner?FACILITY.scannerDamage:f.patrol==='aggressive'?26:FACILITY.patrolDamage));if(!p.health)p.queue=[];p.nextFacilityDamageAt=now+FACILITY.hazardMs;room.survival.alert=Math.min(100,room.survival.alert+2);changed=true;}
 return changed;
}
export function facilityRecalculate(room:R){const f=room.facility;f.sync=f.sync.filter(c=>room.players.has(c.playerId));f.observations=f.observations.filter(c=>room.players.has(c.playerId));f.contributions=f.contributions.filter(c=>room.players.has(c.playerId));if(f.stage===2&&f.routing&&f.contributions.length>=requiredOperators(room.players.size)&&room.players.size)f.stage=3;}
