import {PORTAL,PORTAL_STATIONS,PORTAL_SUPPLIES,portalPressure,type PortalState} from '../shared/portal.js';
import type {PortalAction} from '../shared/protocol.js';
type P={id:string;nickname:string;x:number;z:number;health:number;socketId:string|null;requests:Set<string>;queue:unknown[];nextPortalDamageAt?:number};
type R={players:Map<string,P>;facility:{stage:number};survival:{energy:number;resources:number;alert:number};portal:PortalState};
const required=(r:R)=>Math.min(2,r.players.size);
function validContributions(r:R,now:number){return r.portal.contributors.filter(c=>{const p=r.players.get(c.playerId),t=PORTAL_STATIONS[c.station as 'west'|'east'];return p&&p.socketId&&p.health>0&&c.until>now&&Math.hypot(p.x-t.x,p.z-t.z)<PORTAL.range;});}
function finish(r:R,now:number,timeout=false){const f=r.portal;if(f.status==='RESOLVED')return;const safe=!timeout&&f.decision==='return'&&f.route==='stable'&&f.repaired&&r.survival.alert<PORTAL.highAlert&&[...r.players.values()].every(p=>p.socketId&&p.health>0&&Math.hypot(p.x,p.z+144)<8);
 const kind=timeout?'stranded':f.decision==='helix'?'helix':safe?'return':'costly';const titles={return:'HOME / 2026',costly:'THE PRICE OF A SECOND',stranded:'STRANDED / 2126',helix:'THE HELIX ACCORD'};
 const stories={return:'Every explorer returns to 2026. Stable power, repaired coils and a reunited team kept the timeline intact.',costly:'The emergency crossing reaches 2026 with a cost: unstable power scars the timeline. Disconnected, downed or distant explorers remain in 2126.',stranded:'The deadline expired before a shared crossing was confirmed. The portal collapsed; your team remains in 2126.',helix:'You entrusted the timeline to HELIX. The team stays in 2126 as partners of the AI, opening a new future instead of returning home.'};
 f.ending={kind,title:titles[kind],story:stories[kind],resolvedAt:now,energy:r.survival.energy,materials:r.survival.resources,alert:r.survival.alert,route:f.route,decision:f.decision,players:[...r.players.values()].map(p=>({id:p.id,nickname:p.nickname,health:p.health,connected:!!p.socketId,escaped:(kind==='return'||kind==='costly')&&!!p.socketId&&p.health>0&&Math.hypot(p.x,p.z+144)<8}))};f.status='RESOLVED';f.deadline=0;f.result=stories[kind];for(const p of r.players.values())p.queue=[];
}
function activate(r:R,now:number){const f=r.portal;f.status='ACTIVE';f.deadline=now+PORTAL.activeMs;f.contributors=[];f.result='Portal active for 30 seconds. Agree at the DECISION console, then approach CROSSING.';}
export function portalTick(r:R,now:number){const f=r.portal;if(f.status==='RESOLVED')return false;let changed=false;
 if(f.status==='LOCKED'&&r.facility.stage>=3){f.status='READY';f.result='Enter the Timefall chamber. Collect emergency supplies; select power at CORE.';changed=true;}
 if(['CHARGING','UNSTABLE','ACTIVE'].includes(f.status)&&now>=f.deadline){finish(r,now,true);return true;}
 if(f.status==='CHARGING'||f.status==='UNSTABLE'){const v=validContributions(r,now);if(v.length!==f.contributors.length){f.contributors=v;changed=true;}f.required=required(r);if(v.length>=f.required&&f.required>0){activate(r,now);changed=true;}}
 if(['CHARGING','UNSTABLE','ACTIVE'].includes(f.status)&&f.security==='active'){const field=portalPressure(now);for(const p of r.players.values()){if(!p.socketId||p.health<=0||now<(p.nextPortalDamageAt??0)||Math.hypot(p.x-field.x,p.z-field.z)>=field.radius)continue;p.health=Math.max(0,p.health-PORTAL.damage-(r.survival.alert>=PORTAL.highAlert?10:0));if(!p.health)p.queue=[];p.nextPortalDamageAt=now+PORTAL.damageMs;r.survival.alert=Math.min(100,r.survival.alert+3);changed=true;}}
 return changed;
}
export function portalAction(r:R,p:P,a:PortalAction,now:number,fail:(ok:unknown,code:string)=>void){const f=r.portal,s=r.survival;fail(a.eventId===f.id,'STALE_EVENT');fail(!p.requests.has(a.requestId),'DUPLICATE_ACTION');portalTick(r,now);fail(f.status!=='RESOLVED','EVENT_RESOLVED');fail(p.health>0,'INCAPACITATED');fail(r.facility.stage>=3&&f.status!=='LOCKED','FACILITY_LOCKED');
 const near=(t:{x:number;z:number})=>fail(Math.hypot(p.x-t.x,p.z-t.z)<PORTAL.range,'OUT_OF_RANGE');
 const spend=(e:number,m:number)=>{fail(s.energy>=e&&s.resources>=m,'INSUFFICIENT_SUPPLIES');s.energy-=e;s.resources-=m;};
 if(a.kind==='collect'){const item=PORTAL_SUPPLIES.find(i=>i.id===a.target);fail(item,'INVALID_TARGET');near(item!);fail(!f.collected.includes(a.target),'ALREADY_COLLECTED');f.collected.push(a.target);if(item!.kind==='energy')s.energy=Math.min(100,s.energy+item!.amount);else if(item!.kind==='resources')s.resources=Math.min(20,s.resources+item!.amount);else p.health=Math.min(100,p.health+item!.amount);f.result='Emergency portal supply recovered.';}
 else if(a.kind==='route'){fail(f.status==='READY','BAD_PHASE');near(PORTAL_STATIONS.core);fail(a.target==='stable'||a.target==='surge','INVALID_TARGET');if(a.target==='stable')spend(PORTAL.energyCost,0);else s.alert=Math.min(100,s.alert+15);f.route=a.target as 'stable'|'surge';f.status=a.target==='stable'?'CHARGING':'UNSTABLE';f.deadline=now+PORTAL.chargeMs;f.required=required(r);f.result='Two explorers hold WEST/EAST coils within 15 seconds. Stay at the controls. Security sweeps the center.';}
 else if(a.kind==='stabilize'){fail(f.status==='CHARGING'||f.status==='UNSTABLE','BAD_PHASE');fail(a.target==='west'||a.target==='east','INVALID_TARGET');near(PORTAL_STATIONS[a.target as 'west'|'east']);f.contributors=validContributions(r,now);fail(!f.contributors.some(c=>c.playerId===p.id),'DUPLICATE_CONTRIBUTION');fail(!f.contributors.some(c=>c.station===a.target),'ROLE_TAKEN');f.contributors.push({playerId:p.id,station:a.target,until:now+PORTAL.syncMs});if(f.contributors.length>=required(r))activate(r,now);}
 else if(a.kind==='repair'){fail(['CHARGING','UNSTABLE','ACTIVE'].includes(f.status),'BAD_PHASE');near(PORTAL_STATIONS.repair);fail(a.target==='coils','INVALID_TARGET');fail(!f.repaired,'EVENT_RESOLVED');spend(0,PORTAL.repairCost);f.repaired=true;f.result='Coils repaired. A stable return now depends on low Alert and everyone gathering at CROSSING.';}
 else if(a.kind==='security'){fail(['CHARGING','UNSTABLE','ACTIVE'].includes(f.status),'BAD_PHASE');near(PORTAL_STATIONS.security);fail(a.target==='disable','INVALID_TARGET');fail(f.security==='active','EVENT_RESOLVED');spend(0,1);f.security='disabled';s.alert=Math.max(0,s.alert-10);f.result='Final sentry disabled. Alert reduced by 10.';}
 else if(a.kind==='vote'){fail(f.status==='ACTIVE'&&!f.decision,'BAD_PHASE');near(PORTAL_STATIONS.decision);f.votes=f.votes.filter(c=>(r.players.get(c.playerId)?.health??0)>0);fail(a.target==='return'||a.target==='helix','INVALID_TARGET');fail(!f.votes.some(c=>c.playerId===p.id),'DUPLICATE_CONTRIBUTION');fail(!f.votes.length||f.votes[0].choice===a.target,'TEAM_CHOICE');f.votes.push({playerId:p.id,choice:a.target});if(f.votes.length>=required(r)){f.decision=a.target as 'return'|'helix';f.result='Team choice confirmed. Gather every explorer at CROSSING and confirm.';}else f.result='One vote recorded. A different explorer must confirm the same choice at DECISION.';}
 else {fail(a.kind==='cross'&&a.target==='crossing','INVALID_TARGET');fail(f.status==='ACTIVE'&&f.decision,'BAD_PHASE');near(PORTAL_STATIONS.exit);finish(r,now);}
 p.requests.add(a.requestId);if(p.requests.size>64)p.requests.delete(p.requests.values().next().value!);
}
export function portalRecalculate(r:R,now:number){const f=r.portal;if(f.status==='RESOLVED')return;f.required=required(r);f.contributors=f.contributors.filter(c=>r.players.has(c.playerId));f.votes=f.votes.filter(c=>r.players.has(c.playerId));if(!f.decision&&f.votes.length>=f.required&&f.required>0)f.decision=f.votes[0].choice as 'return'|'helix';portalTick(r,now);}
