import * as T from 'three';import {FACILITY_WALLS,STATIONS,CACHES,type FacilityState} from '../shared/facility';
export function buildFacility(scene:T.Scene){
 const root=new T.Group();scene.add(root);const boxGeo=new T.BoxGeometry(1,1,1),dark=new T.MeshStandardMaterial({color:0x122d37,roughness:.85}),wall=new T.MeshStandardMaterial({color:0x335265,roughness:.75}),cyan=new T.MeshBasicMaterial({color:0x71ffee}),amber=new T.MeshBasicMaterial({color:0xffc577}),red=new T.MeshBasicMaterial({color:0xff5469,transparent:true,opacity:.22,depthWrite:false}),violet=new T.MeshBasicMaterial({color:0xbf98ff});const solids:T.Object3D[]=[];const staticMeshes:T.Mesh[]=[];
 const box=(x:number,y:number,z:number,w:number,h:number,d:number,mat:T.Material,solid=false,dynamic=false)=>{const m=new T.Mesh(boxGeo,mat);m.position.set(x,y,z);m.scale.set(w,h,d);root.add(m);if(!dynamic)staticMeshes.push(m);if(solid)solids.push(m);return m;};
 const label=(text:string,x:number,z:number,color='#71ffee',y=2.3,w=3.5)=>{const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d')!;ctx.fillStyle='#0b1824';ctx.fillRect(0,0,512,96);ctx.fillStyle=color;ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,58);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(w,.65),new T.MeshBasicMaterial({map:texture}));mesh.position.set(x,y,z);root.add(mesh);return mesh;};
 box(0,-.1,-77,20,.2,70,dark);for(const b of FACILITY_WALLS)box((b.minX+b.maxX)/2,2.5,(b.minZ+b.maxZ)/2,b.maxX-b.minX,5,b.maxZ-b.minZ,wall,true);
 // Open ceilings keep the third-person camera usable; frames define real chambers.
 for(const z of [-46,-54,-68,-78,-96,-106]){box(0,5.4,z,21,.4,.6,dark);for(const x of [-9,9]){box(x,2.6,z,.5,5.2,.6,wall);box(x,2.6,z+.35,.1,4,.1,cyan);}}
 for(const x of [-8.7,8.7])box(x,.03,-78,.09,.06,65,cyan);
 for(const [z,text] of [[-45,'HELIX / AI RESEARCH'],[-57,'01 / MEMORY VAULT'],[-73,'02 / REACTOR WING'],[-99,'03 / PORTAL TRANSIT']] as const)label(text,0,z,'#bf98ff',4.3,6);
 const gates=[box(0,2,-46,19,4,.8,amber,true,true),box(0,2,-68,10,4,.8,violet,true,true),box(0,2,-96,10,4,.8,amber,true,true),box(0,2,-106,19,4,.8,violet,true,true)];
 for(const [id,t] of Object.entries(STATIONS)){box(t.x,.65,t.z,.9,1.3,.7,dark);box(t.x,1.35,t.z,.95,.15,.8,id==='alpha'||id==='beta'?violet:cyan);label(id.toUpperCase(),t.x,t.z+.5,'#71ffee',2,2.2);}
 const cacheMeshes=CACHES.map(c=>({id:c.id,mesh:box(c.x,.4,c.z,.6,.8,.6,c.kind==='medical'?violet:c.kind==='energy'?cyan:amber,false,true)}));
 const scanner=new T.Group();scanner.position.set(0,3,-60);const lens=new T.Mesh(new T.OctahedronGeometry(.7),violet);scanner.add(lens);root.add(scanner);const scannerField=new T.Mesh(new T.CircleGeometry(3.2,24),red);scannerField.rotation.x=-Math.PI/2;scannerField.position.set(0,.05,-60);root.add(scannerField);
 const patrol=new T.Group();for(const x of [-.45,.45]){const leg=new T.Mesh(boxGeo,wall);leg.position.set(x,.6,0);leg.scale.set(.3,1.2,.35);patrol.add(leg);}const body=new T.Mesh(boxGeo,dark);body.position.y=1.5;body.scale.set(1.3,1,.7);patrol.add(body);const eye=new T.Mesh(boxGeo,amber);eye.position.set(0,1.7,.38);eye.scale.set(.7,.15,.05);patrol.add(eye);root.add(patrol);const patrolField=new T.Mesh(new T.CircleGeometry(2.2,24),red);patrolField.rotation.x=-Math.PI/2;root.add(patrolField);
 // Instance all static cuboids into four material batches.
 const batches=new Map<T.Material,T.Mesh[]>();root.updateMatrixWorld(true);for(const m of staticMeshes){const mat=m.material as T.Material;const list=batches.get(mat)||[];list.push(m);batches.set(mat,list);root.remove(m);}for(const [mat,list] of batches){const instance=new T.InstancedMesh(boxGeo,mat,list.length);list.forEach((m,i)=>instance.setMatrixAt(i,m.matrixWorld));instance.computeBoundingSphere();root.add(instance);}
 const ray=new T.Raycaster();return {update(f:FacilityState,serverTime:number,objective:number,resolved:boolean){const closed=[objective<2||!resolved||f.stage<1,f.stage<2,f.stage<3,f.stage<3];gates.forEach((g,i)=>g.visible=closed[i]);cacheMeshes.forEach(c=>c.mesh.visible=!f.collected.includes(c.id));scanner.visible=f.scanner==='active';scannerField.visible=f.stage>=1&&f.scanner==='active'&&serverTime>=f.scannerUntil;patrol.visible=f.stage>=2;const x=Math.sin(serverTime/1800)*4;patrol.position.set(x,0,-86);patrolField.position.set(x,.06,-86);patrolField.visible=f.stage>=2&&f.patrol!=='diverted';lens.rotation.y=serverTime/1500;},cameraPosition(target:T.Vector3,wanted:T.Vector3){const d=wanted.clone().sub(target),distance=d.length();ray.set(target,d.normalize());ray.far=distance;const hit=ray.intersectObjects(solids.filter(s=>s.visible),false)[0];return hit?target.clone().addScaledVector(d,Math.max(.15,hit.distance-.2)):wanted;}};
}
