import * as T from 'three';import {buildWorld,buildAvatar} from './world';import {controls} from './controls';import {move,blocked} from './collision.js';import {Network} from './network';import type {RoomState,PublicPlayer} from '../shared/protocol';import './style.css';
const $=<E extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as E;
let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({canvas:$<HTMLCanvasElement>('world'),antialias:true,powerPreference:'high-performance'});}catch(error){$('fatal').hidden=false;$('fatal').textContent='WebGL could not start. Try an up-to-date browser with hardware acceleration enabled. '+String(error);$('start').hidden=true;throw error;}
renderer.setClearColor(0x0b1929);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.fog=new T.FogExp2(0x152d42,.012);scene.add(new T.HemisphereLight(0x95d3e8,0x263647,2.2));const sun=new T.DirectionalLight(0xa4dcff,2.5);sun.position.set(-15,25,10);scene.add(sun);const rim=new T.DirectionalLight(0xcba3ff,1);rim.position.set(10,12,-30);scene.add(rim);
const camera=new T.PerspectiveCamera(57,innerWidth/innerHeight,.1,180),world=buildWorld(scene),avatar=buildAvatar(scene),position=avatar.group.position,net=new Network();
const input=controls($<HTMLCanvasElement>('world'),interact);let started=false,intro=false,introStart=0,elapsed=0,last=performance.now(),stage=0,shownEpoch=-1,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,quality='Auto',low=false,messageUntil=0,frames=0,sampleStart=last,fps=0,frameMs=0,ready=false,resizeCount=0,mode:'create'|'join'='create';
const fpsHistory:number[]=[];let interactionCount=0,cameraClamped=false;
type Remote={avatar:ReturnType<typeof buildAvatar>;label:HTMLDivElement;history:{t:number;x:number;z:number;angle:number}[];player:PublicPlayer};const remotes=new Map<string,Remote>();
$<HTMLInputElement>('reduceMotion').checked=reduced;
function resize(){renderer.setPixelRatio(low?1:Math.min(devicePixelRatio,input.touch?1.35:1.6));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<innerHeight?65:57;camera.updateProjectionMatrix();resizeCount++;}window.addEventListener('resize',resize);resize();
function notify(text:string){if(started){$('message').textContent=text;$('message').classList.add('visible');messageUntil=elapsed+5;}else if(net.state){$('lobbyError').textContent=text;}else $('formError').textContent=text;}
function clearRemotes(){for(const remote of remotes.values()){remote.avatar.dispose();remote.label.remove();}remotes.clear();}
function syncRemotes(state:RoomState){const ids=new Set(state.players.filter(p=>p.id!==net.session?.playerId).map(p=>p.id));for(const [id,remote] of remotes)if(!ids.has(id)){remote.avatar.dispose();remote.label.remove();remotes.delete(id);}for(const p of state.players){if(p.id===net.session?.playerId)continue;let remote=remotes.get(p.id);if(!remote){const label=document.createElement('div');label.className='remote-label';label.style.borderColor=p.color;$('remoteLabels').append(label);remote={avatar:buildAvatar(scene,new T.Color(p.color).getHex()),label,history:[],player:p};remote.avatar.group.position.set(p.x,0,p.z);remotes.set(p.id,remote);}remote.player=p;remote.label.textContent=p.nickname+(p.connected?'':' · reconnecting');remote.label.classList.toggle('offline',!p.connected);const sample={t:state.serverTime,x:p.x,z:p.z,angle:p.angle};if(remote.history.at(-1)?.t===sample.t)remote.history[remote.history.length-1]=sample;else remote.history.push(sample);if(remote.history.length>20)remote.history.shift();}}
function updateObjective(){const titles=['Find the emergency beacon','Trace the portal signal','A way home. Beyond the barrier.'],details=['Approach the cyan beacon. One team scan updates everyone.','Follow the avenue to the amber transit barrier.','Team survey complete. The portal route continues in later milestones.'];$('objective').textContent=titles[stage];$('objectiveDetail').textContent=details[stage];$('step').textContent=`0${stage+1} / 03`;$('progress').style.width=['6%','55%','100%'][stage];}
function beginGame(state:RoomState){started=true;shownEpoch=state.epoch;intro=Date.now()+net.offset<state.arrivalEndsAt;introStart=elapsed-Math.max(0,(Date.now()+net.offset-state.startedAt)/1000);position.set(net.prediction.x,0,net.prediction.z);input.reset(true);$('start').hidden=true;$('hud').hidden=false;$('introCaption').hidden=!intro;$('letterbox').hidden=!intro||reduced;$('introFX').hidden=!intro||reduced;$('introFX').style.animation='none';void $('introFX').offsetWidth;$('introFX').style.animation='';$<HTMLDialogElement>('helpDialog').close();updateObjective();}
function endIntro(){intro=false;input.reset();$('introCaption').hidden=true;$('introFX').hidden=true;$('letterbox').hidden=true;notify(input.touch?'Move with the joystick. Drag the right side to look.':'Move with WASD or arrows. Drag the world to look.');}
function showMenu(){started=intro=false;shownEpoch=-1;input.reset(true);clearRemotes();position.set(0,0,11);avatar.setColor('#62edff');$('start').hidden=false;$('roomMenu').hidden=false;$('lobby').hidden=true;$('hud').hidden=true;$('connectionBanner').hidden=true;$('introCaption').hidden=true;$('introFX').hidden=true;$('letterbox').hidden=true;$('formError').textContent='';}
function renderLobby(state:RoomState){started=intro=false;shownEpoch=-1;input.reset();clearRemotes();$('start').hidden=false;$('roomMenu').hidden=true;$('lobby').hidden=false;$('hud').hidden=true;$('introCaption').hidden=true;$('introFX').hidden=true;$('letterbox').hidden=true;$('lobbyCode').textContent=state.code;const connected=state.players.filter(p=>p.connected);$('playerCount').textContent=`${connected.length} connected / ${state.players.length} reserved / 6 max`;
 const list=$('playerList');list.replaceChildren();for(const p of state.players){const li=document.createElement('li');li.dataset.playerId=p.id;const color=document.createElement('span');color.className='player-color';color.style.background=p.color;const name=document.createElement('span');name.className='player-name';name.textContent=p.nickname+(p.id===net.session?.playerId?' (you)':'');if(state.hostId===p.id){const host=document.createElement('span');host.className='player-role';host.textContent='HOST';name.append(host);}const status=document.createElement('span');status.className='player-status'+(!p.connected?' offline':p.ready?' ready':'');status.textContent=!p.connected?'Reconnecting':p.ready?'Ready':'Not ready';li.append(color,name,status);list.append(li);}
 $('readyButton').textContent=net.me?.ready?'Not ready':'Ready';const canStart=connected.length>=2&&connected.every(p=>p.ready),host=state.hostId===net.session?.playerId;$('startGame').hidden=!host;$<HTMLButtonElement>('startGame').disabled=!canStart||!net.connected;$<HTMLButtonElement>('readyButton').disabled=!net.connected;$('lobbyHint').textContent=connected.length<2?'Share the code. At least two connected explorers are needed.':!canStart?'Every connected explorer must select Ready.':host?'Your team is ready. Start the expedition.':'Your team is ready. Waiting for the host to start.';}
net.onState=state=>{stage=state.objective.stage;interactionCount=stage;avatar.setColor(net.me?.color??'#62edff');$('hudRoom').textContent='ROOM '+state.code;$('hudPlayers').textContent=`${state.players.filter(p=>p.connected).length}/${state.players.length} explorers`;$('reset').hidden=state.hostId!==net.session?.playerId;
 if(state.phase==='lobby')renderLobby(state);else{if(!started||shownEpoch!==state.epoch)beginGame(state);syncRemotes(state);updateObjective();}};
net.onNotice=notify;net.onStatus=text=>{for(const id of ['menuConnection','lobbyConnection','hudConnection'])$(id).textContent=text;$<HTMLButtonElement>('submitRoom').disabled=!net.connected;const disconnected=Boolean(net.session)&&!net.connected;$('connectionBanner').hidden=!disconnected;$('connectionBanner').textContent='Reconnecting… Your place is reserved for up to 90 seconds.';if(disconnected)input.reset();if(!net.session&&started)showMenu();};
function choose(next:'create'|'join'){mode=next;$('codeField').hidden=mode!=='join';$<HTMLInputElement>('roomCode').required=mode==='join';$('submitRoom').textContent=mode==='create'?'Create room':'Join room';for(const [id,value] of [['createMode','create'],['joinMode','join']]){$(id).classList.toggle('selected',mode===value);$(id).setAttribute('aria-pressed',String(mode===value));}$('formError').textContent='';}
$('createMode').addEventListener('click',()=>choose('create'));$('joinMode').addEventListener('click',()=>choose('join'));
$('roomForm').addEventListener('submit',async e=>{e.preventDefault();$('formError').textContent='';$<HTMLButtonElement>('submitRoom').disabled=true;const nickname=$<HTMLInputElement>('nickname').value.trim(),code=$<HTMLInputElement>('roomCode').value.trim();if(!nickname){$('formError').textContent='Choose a display nickname.';$<HTMLButtonElement>('submitRoom').disabled=!net.connected;return;}const reply=await net.request(mode==='create'?'room:create':'room:join',mode==='create'?{nickname}:{nickname,code});if(!reply.ok)$('formError').textContent=reply.message;$<HTMLButtonElement>('submitRoom').disabled=!net.connected;});
$('readyButton').addEventListener('click',async()=>{if(!net.state)return;const reply=await net.request('room:ready',{ready:!net.me?.ready,epoch:net.state.epoch});if(!reply.ok)notify(reply.message);});
$('startGame').addEventListener('click',async()=>{if(!net.state)return;const reply=await net.request('room:start',{epoch:net.state.epoch});if(!reply.ok)notify(reply.message);});
async function leave(){const reply=await net.leave();if(reply.ok){$<HTMLDialogElement>('helpDialog').close();showMenu();}else notify(reply.message);}$('leaveLobby').addEventListener('click',leave);$('leaveGame').addEventListener('click',leave);
$('skip').addEventListener('click',endIntro);$('interact').addEventListener('click',interact);$('help').addEventListener('click',()=>{input.reset();$<HTMLDialogElement>('helpDialog').showModal();});$('closeHelp').addEventListener('click',()=>$<HTMLDialogElement>('helpDialog').close());$('reset').addEventListener('click',async()=>{if(!net.state)return;const reply=await net.request('room:reset',{epoch:net.state.epoch});if(reply.ok)$<HTMLDialogElement>('helpDialog').close();else notify(reply.message);});
$<HTMLInputElement>('reduceMotion').addEventListener('change',e=>{reduced=(e.target as HTMLInputElement).checked;if(intro)endIntro();});$('quality').addEventListener('click',()=>{quality=quality==='Auto'?'Low':quality==='Low'?'High':'Auto';low=quality==='Low';$('quality').textContent='Quality: '+quality;resize();});$('metricsToggle').addEventListener('click',()=>{$('metrics').hidden=!$('metrics').hidden;});
async function interact(){if(!started||intro||!net.connected||document.querySelector('dialog[open]')||stage>1)return;await net.interact(stage===0?'beacon':'signal');}
net.getInput=()=>{if(!started||intro||!net.connected||document.querySelector('dialog[open]')||document.hidden)return {x:0,z:0};const m=input.movement(),sin=Math.sin(input.yaw),cos=Math.cos(input.yaw);return {x:m.x*cos-m.y*sin,z:-m.x*sin-m.y*cos};};
function updateUI(){const nearBeacon=Math.hypot(position.x,position.z+7)<2.8,nearVista=Math.hypot(position.x,position.z+38)<4,stabilizing=Date.now()+net.offset<(net.state?.arrivalEndsAt??0);$('location').textContent=position.z>1?'ARRIVAL ZONE':position.z>-30?'ABANDONED CITY':'NORTH TRANSIT BARRIER';$('coordinates').textContent=`X ${position.x.toFixed(0)} / Z ${position.z.toFixed(0)}`;ready=net.connected&&!intro&&!stabilizing&&((stage===0&&nearBeacon)||(stage===1&&nearVista));$<HTMLButtonElement>('interact').disabled=!ready;$('actionLabel').textContent=stage===0?'Scan beacon':stage===1?'Trace signal':'Survey complete';$('prompt').textContent=!net.connected?'Waiting for reconnection':intro||stabilizing?'Arrival stabilizing…':stage===0?(nearBeacon?'Emergency beacon within reach':'Follow the cyan beacon'):stage===1?(nearVista?'Portal signal within range':'Reach the north transit barrier'):'Explore together · Survey complete';}
const target=new T.Vector3(),wanted=new T.Vector3(),labelPoint=new T.Vector3();
function updateRemotes(){const renderTime=Date.now()+net.offset-120;for(const remote of remotes.values()){const history=remote.history;let a=history[0],b=history.at(-1)!;for(let i=1;i<history.length;i++)if(history[i].t>=renderTime){a=history[i-1];b=history[i];break;}else a=history[i];const fraction=b.t===a.t?1:Math.max(0,Math.min(1,(renderTime-a.t)/(b.t-a.t)));const x=T.MathUtils.lerp(a.x,b.x,fraction),z=T.MathUtils.lerp(a.z,b.z,fraction),moving=Math.hypot(x-remote.avatar.group.position.x,z-remote.avatar.group.position.z)>.005;remote.avatar.group.position.set(x,0,z);const delta=Math.atan2(Math.sin(b.angle-a.angle),Math.cos(b.angle-a.angle));remote.avatar.group.rotation.y=a.angle+delta*fraction;remote.avatar.animate(elapsed,moving&&remote.player.connected);labelPoint.set(x,2.4,z).project(camera);const visible=labelPoint.z>-1&&labelPoint.z<1&&Math.abs(labelPoint.x)<1&&Math.abs(labelPoint.y)<1&&position.distanceTo(remote.avatar.group.position)<40;remote.label.hidden=!visible;remote.label.style.transform=`translate(${(labelPoint.x*.5+.5)*innerWidth}px,${(-labelPoint.y*.5+.5)*innerHeight}px) translate(-50%,-100%)`;}}
function tick(now:number){requestAnimationFrame(tick);const rawDt=(now-last)/1000,dt=Math.min(rawDt,.05);last=now;elapsed+=rawDt;if(started&&intro&&elapsed-introStart>(reduced?1.2:4.5))endIntro();let moving=false;
 if(started&&net.connected){const deltaX=net.prediction.x-position.x,deltaZ=net.prediction.z-position.z;moving=Math.hypot(deltaX,deltaZ)>.003;const alpha=Math.min(1,dt*24),next=move(position,deltaX*alpha,deltaZ*alpha,world.boxes);position.x=next.x;position.z=next.z;const m=net.getInput();if(Math.hypot(m.x,m.z)>.05){const angle=Math.atan2(-m.x,-m.z),difference=Math.atan2(Math.sin(angle-avatar.group.rotation.y),Math.cos(angle-avatar.group.rotation.y));avatar.group.rotation.y+=difference*Math.min(1,dt*12);}}
 avatar.animate(elapsed,moving);world.animate(elapsed,reduced);if(!started){avatar.group.visible=true;camera.position.set(5,5,19);camera.lookAt(0,2,-17);}else{target.set(position.x,1.4,position.z);let yaw=input.yaw,dist=input.distance,pitch=input.pitch;if(intro&&!reduced){const p=Math.min(1,(elapsed-introStart)/4.5);yaw=(1-p)*.7;dist=7+(1-p)*5;pitch=.28+(1-p)*.12;}wanted.set(target.x+Math.sin(yaw)*Math.cos(pitch)*dist,target.y+Math.sin(pitch)*dist,target.z+Math.cos(yaw)*Math.cos(pitch)*dist);const safe=world.cameraPosition(target,wanted);safe.y=Math.max(.55,safe.y);cameraClamped=safe.distanceTo(wanted)>.1;camera.position.copy(safe);camera.lookAt(target);avatar.group.visible=camera.position.distanceTo(target)>1.1;updateUI();updateRemotes();}
 if(elapsed>messageUntil)$('message').classList.remove('visible');renderer.render(scene,camera);frames++;if(now-sampleStart>=1000){fps=frames*1000/(now-sampleStart);frameMs=(now-sampleStart)/frames;fpsHistory.push(fps);if(fpsHistory.length>60)fpsHistory.shift();frames=0;sampleStart=now;if(quality==='Auto'&&!low&&fpsHistory.length>=6&&fpsHistory.slice(-6).every(v=>v<26)){low=true;resize();notify('Rendering quality reduced for smoother exploration.');}const size=renderer.getDrawingBufferSize(new T.Vector2());$('metrics').textContent=`${fps.toFixed(1)} FPS · ${frameMs.toFixed(1)} ms/frame\n${renderer.info.render.calls} draw calls\n${renderer.info.render.triangles.toLocaleString()} triangles\nBuffer ${size.x} × ${size.y}\nDPR ${renderer.getPixelRatio().toFixed(2)} · ${low?'Low':quality}\n${remotes.size+1} avatars · 20 Hz input / 10 Hz state`;} }
const view=()=>({started,intro,stage,player:{x:position.x,z:position.z},camera:{x:camera.position.x,y:camera.position.y,z:camera.position.z,yaw:input.yaw,pitch:input.pitch,distance:input.distance,clamped:cameraClamped},blocked:blocked(position.x,position.z,world.boxes),ready,interactionCount,touch:input.touch,quality,low,fps,frameMs,fpsHistory:[...fpsHistory],drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,pixelRatio:renderer.getPixelRatio(),viewport:{width:innerWidth,height:innerHeight},resizeCount,boxes:world.boxes.map(b=>({...b})),remotePlayers:[...remotes].map(([id,r])=>({id,nickname:r.player.nickname,connected:r.player.connected,x:r.avatar.group.position.x,z:r.avatar.group.position.z,history:r.history.length})),network:net.diagnostics()});
Object.defineProperty(window,'__M2',{get:view});Object.defineProperty(window,'__M1',{get:view});$<HTMLCanvasElement>('world').addEventListener('webglcontextlost',e=>{e.preventDefault();input.reset();$('fatal').hidden=false;$('fatal').textContent='The graphics connection was interrupted. Reload to restore your reserved place.';});requestAnimationFrame(tick);net.start();
