import * as T from 'three';import {PORTAL_WALLS,PORTAL_STATIONS,PORTAL_SUPPLIES,portalPressure,type PortalState} from '../shared/portal';
export function buildPortal(scene:T.Scene,landmark:T.Mesh){const root=new T.Group();scene.add(root);const geo=new T.BoxGeometry(1,1,1),dark=new T.MeshStandardMaterial({color:0x183247,roughness:.8}),metal=new T.MeshStandardMaterial({color:0x46677a,roughness:.6}),glow=new T.MeshBasicMaterial({color:0x72ffdf}),amber=new T.MeshBasicMaterial({color:0xffb66c}),red=new T.MeshBasicMaterial({color:0xff5469,transparent:true,opacity:.2,depthWrite:false});const solids:T.Object3D[]=[],batches=new Map<T.Material,T.Matrix4[]>();
 function box(x:number,y:number,z:number,w:number,h:number,d:number,mat:T.Material,solid=false){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(w,h,d);m.updateMatrix();const list=batches.get(mat)||[];list.push(m.matrix.clone());batches.set(mat,list);if(solid){m.updateMatrixWorld();solids.push(m);}return m;}
 box(0,-.08,-132,20,.16,40,dark);for(const b of PORTAL_WALLS)box((b.minX+b.maxX)/2,2.5,(b.minZ+b.maxZ)/2,b.maxX-b.minX,5,b.maxZ-b.minZ,metal,true);for(const z of [-114,-124,-136,-150]){box(0,6,z,20,.4,.4,metal);for(const x of [-9,9]){box(x,3,z,.4,6,.4,metal);box(x,.1,z,.8,.1,3,glow);}}for(const x of [-8,8])box(x,.03,-133,.08,.06,35,glow);
 const c=document.createElement('canvas');c.width=1024;c.height=512;const ctx=c.getContext('2d')!;ctx.fillStyle='#101d31';ctx.fillRect(0,0,1024,512);ctx.fillStyle='#72ffdf';ctx.textAlign='center';ctx.font='bold 42px sans-serif';const names=Object.keys(PORTAL_STATIONS);names.forEach((id,i)=>ctx.fillText(id==='exit'?'CROSSING':id.toUpperCase(),256+(i%2)*512,48+Math.floor(i/2)*128));const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const labels=new T.BufferGeometry(),positions:number[]=[],uv:number[]=[],indices:number[]=[];Object.entries(PORTAL_STATIONS).forEach(([id,t],i)=>{box(t.x,.6,t.z,.8,1.2,.7,dark);box(t.x,1.25,t.z,1,.15,.8,glow);const x=t.x,y=2.2,z=t.z+.4,n=i*4;positions.push(x-1.2,y-.25,z,x+1.2,y-.25,z,x+1.2,y+.25,z,x-1.2,y+.25,z);const u=(i%2)*.5,v=1-Math.floor(i/2)*.25;uv.push(u,v-.25,u+.5,v-.25,u+.5,v,u,v);indices.push(n,n+1,n+2,n,n+2,n+3);});labels.setAttribute('position',new T.Float32BufferAttribute(positions,3));labels.setAttribute('uv',new T.Float32BufferAttribute(uv,2));labels.setIndex(indices);root.add(new T.Mesh(labels,new T.MeshBasicMaterial({map:texture})));
 for(const [mat,list] of batches){const inst=new T.InstancedMesh(geo,mat,list.length);list.forEach((m,i)=>inst.setMatrixAt(i,m));inst.computeBoundingSphere();root.add(inst);}
 const supplies=PORTAL_SUPPLIES.map(i=>{const m=new T.Mesh(geo,i.kind==='resources'?amber:glow);m.position.set(i.x,.4,i.z);m.scale.set(.6,.8,.6);root.add(m);return {id:i.id,m};});const sentry=new T.Mesh(new T.OctahedronGeometry(.6),amber);root.add(sentry);const field=new T.Mesh(new T.CircleGeometry(2.4,16),red);field.rotation.x=-Math.PI/2;root.add(field);
 const aperture=new T.Mesh(new T.CircleGeometry(4.4,32),new T.MeshBasicMaterial({color:0x72ffdf,transparent:true,opacity:.5,side:T.DoubleSide,depthWrite:false}));aperture.position.set(0,6.8,-127.04);root.add(aperture);const ray=new T.Raycaster();
 return {update(f:PortalState,time:number,reduced:boolean){supplies.forEach(s=>s.m.visible=!f.collected.includes(s.id));const busy=['CHARGING','UNSTABLE','ACTIVE'].includes(f.status);const p=portalPressure(time);sentry.position.set(p.x,3,-130);field.position.set(p.x,.08,-130);sentry.visible=field.visible=busy&&f.security==='active';aperture.visible=f.status!=='LOCKED'&&f.status!=='READY';const mat=aperture.material as T.MeshBasicMaterial;mat.color.set(f.ending?.kind==='stranded'||f.status==='UNSTABLE'?0xff5469:f.ending?.kind==='helix'?0xc4a0ff:0x72ffdf);mat.opacity=f.status==='RESOLVED'?.8:f.status==='ACTIVE'?.65:.25+(reduced?0:Math.sin(time/400)*.1);landmark.visible=f.status==='LOCKED'||f.status==='READY';},cameraPosition(target:T.Vector3,wanted:T.Vector3){const d=wanted.clone().sub(target),length=d.length();ray.set(target,d.normalize());ray.far=length;const hit=ray.intersectObjects(solids,false)[0];return hit?target.clone().addScaledVector(d,Math.max(.15,hit.distance-.2)):wanted;}};
}
