import * as T from 'three';import {SUPPLIES,SECURITY,TERMINALS,type SurvivalState} from '../shared/survival';
export function buildSurvivalView(scene:T.Scene){const group=new T.Group();scene.add(group);const supplyMeshes=new Map<string,T.Group>();
 const material=(color:number)=>new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.35,roughness:.6});const cyan=material(0x62edff),amber=material(0xffbd72),green=material(0x8df0a6),red=material(0xff526d),metal=material(0x344f64);
 const box=(parent:T.Group,w:number,h:number,d:number,mat:T.Material,x=0,y=0,z=0)=>{const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);parent.add(mesh);return mesh;};
 const label=(parent:T.Group,text:string,y:number,color='#62edff')=>{const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d')!;ctx.fillStyle='#071a2b';ctx.fillRect(0,0,512,96);ctx.strokeStyle=color;ctx.lineWidth=6;ctx.strokeRect(3,3,506,90);ctx.fillStyle=color;ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,59);const texture=new T.CanvasTexture(c),mesh=new T.Mesh(new T.PlaneGeometry(3,.56),new T.MeshBasicMaterial({map:texture,side:T.DoubleSide}));mesh.position.y=y;parent.add(mesh);};
 for(const item of SUPPLIES){const g=new T.Group();g.position.set(item.x,0,item.z);group.add(g);const mat=item.kind==='energy'?cyan:item.kind==='resources'?amber:green;box(g,.6,.7,.6,mat,0,.6);label(g,item.kind==='energy'?'ENERGY CELL':item.kind==='resources'?'REPAIR MATERIAL':'MEDICAL SUPPLY',1.5,item.kind==='energy'?'#62edff':item.kind==='resources'?'#ffbd72':'#8df0a6');supplyMeshes.set(item.id,g);}
 for(const [role,p] of Object.entries(TERMINALS)){const g=new T.Group();g.position.set(p.x,0,p.z);group.add(g);box(g,.8,1.2,.5,metal,0,.6);box(g,.7,.38,.07,cyan,0,1.2,.3);label(g,role==='prime'?'WEST · POWER':'EAST · GROUND',2);}
 const drone=new T.Group();drone.position.set(SECURITY.x,3.5,SECURITY.z);group.add(drone);box(drone,1.2,.4,.7,metal);box(drone,.45,.2,.1,red,0,0,.42);for(const x of [-.9,.9])box(drone,.65,.08,.85,metal,x,.05);label(drone,'SECURITY DRONE',1,'#ff526d');
 const zone=new T.Mesh(new T.RingGeometry(SECURITY.radius-.12,SECURITY.radius,48),new T.MeshBasicMaterial({color:0xff526d,transparent:true,opacity:.65,side:T.DoubleSide}));zone.rotation.x=-Math.PI/2;zone.position.set(SECURITY.x,.04,SECURITY.z);group.add(zone);
 return {update(s:SurvivalState,t:number,reduced:boolean){for(const [id,g] of supplyMeshes){g.visible=!s.collected.includes(id);if(!reduced)g.children[0].rotation.y=t*.5;}drone.position.y=3.5+(reduced?0:Math.sin(t*1.5)*.15);zone.visible=s.security!=='disabled';drone.rotation.y=s.security==='disabled'?0:Math.sin(t*.6)*.5;(zone.material as T.MeshBasicMaterial).color.set(s.security==='shielded'?0xffbd72:0xff526d);}};
}
