import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {writeFile,readFile,access} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {resolve,dirname} from 'node:path';
const results=[],errors=[],warnings=[],measurements={},screenshots=[];let completed=false;
if(process.env.M1_TEST_PHASE==='mobile'){const prior=JSON.parse(await readFile('evidence/desktop-results.json','utf8'));results.push(...prior.results);errors.push(...prior.errors);warnings.push(...prior.warnings);Object.assign(measurements,prior.measurements);screenshots.push(...prior.screenshots);}
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'3210'},stdio:'pipe'});
await new Promise((res,rej)=>{server.stdout.once('data',res);server.once('error',rej);server.once('exit',code=>rej(Error('Server exited: '+code)));});
let browser;
const record=(name,data)=>{results.push({name,status:'PASS',details:data});console.log('PASS '+name+(data?' '+JSON.stringify(data):''));};
async function check(name,fn){try{record(name,await fn());}catch(e){results.push({name,status:'FAIL',details:e.message});console.log('FAIL '+name+' '+e.message);throw e;}}
const diagnostic=page=>page.evaluate(()=>window.__M1);
async function until(page,fn,timeout=90000){await page.waitForFunction(fn,null,{timeout,polling:'raf'});}
async function held(page,key,fn){await page.keyboard.down(key);try{await until(page,fn);}finally{await page.keyboard.up(key);}}
async function shot(page,name){await page.screenshot({path:'evidence/'+name});screenshots.push(name);}
async function touch(cdp,type,points){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});}
function point(x,y,id){return {x,y,id,radiusX:4,radiusY:4,force:1};}
try{
 const packed=resolve('../browser-runtime/chromium');let executablePath=process.env.CHROMIUM_EXECUTABLE_PATH;try{if(!executablePath){await access(packed);executablePath=packed;}}catch{}
 const launch={headless:true};if(executablePath){Object.assign(launch,{executablePath,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:dirname(executablePath),FONTCONFIG_PATH:resolve(dirname(executablePath),'fonts')}});}
 browser=await chromium.launch(launch);measurements.browser=browser.version();measurements.platform=process.platform;measurements.rendering='Headless Chromium; packaged fallback uses ANGLE SwiftShader software rendering. No physical phone.';
 if(process.env.M1_TEST_PHASE!=='mobile'){
 const context=await browser.newContext({viewport:{width:960,height:640}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());});page.setDefaultTimeout(90000);
 await check('Production server starts and /health responds',async()=>{const response=await page.request.get('http://127.0.0.1:3210/health');assert.equal(response.status(),200);assert.equal((await response.json()).multiplayer,false);return {httpStatus:response.status(),port:3210};});
 await check('WebGL world renders',async()=>{await page.goto('http://127.0.0.1:3210/',{waitUntil:'load'});await until(page,()=>window.__M1?.fpsHistory.length>=3);assert.equal(errors.length,0);await shot(page,'desktop-landing.png');return {drawCalls:(await diagnostic(page)).drawCalls};});
 await check('Intro sequence completes and third-person view is established',async()=>{await page.getByRole('button',{name:'Enter the arrival zone'}).click();await until(page,()=>window.__M1.started&&!window.__M1.intro);const d=await diagnostic(page);assert.ok(d.camera.z>d.player.z);assert.ok(d.camera.y>1);await shot(page,'desktop-arrival.png');return {player:d.player,camera:d.camera};});
 await check('WASD and arrow controls move the player',async()=>{await held(page,'w',()=>window.__M1.player.z<9);const p=(await diagnostic(page)).player;await held(page,'ArrowRight',()=>window.__M1.player.x>1);await held(page,'a',()=>window.__M1.player.x<.1);return {forwardPosition:p,current:(await diagnostic(page)).player};});
 await check('Beacon collision prevents walking through console',async()=>{await held(page,'w',()=>window.__M1.player.z<-5.95);const before=(await diagnostic(page)).player;await page.keyboard.down('w');await page.waitForTimeout(1800);await page.keyboard.up('w');const after=(await diagnostic(page)).player;assert.ok(after.z>=-6.45+.42-.01);assert.equal((await diagnostic(page)).blocked,false);return {before,after};});
 await check('Context prompt, keyboard interaction and duplicate scan handling',async()=>{assert.equal((await diagnostic(page)).ready,true);await page.keyboard.press('e');await until(page,()=>window.__M1.stage===1);await page.keyboard.press('e');assert.equal((await diagnostic(page)).interactionCount,1);assert.match(await page.locator('#objective').innerText(),/Trace the portal signal/);await shot(page,'desktop-beacon.png');});
 await check('City navigation and final local objective',async()=>{await held(page,'d',()=>window.__M1.player.x>2);await held(page,'w',()=>window.__M1.player.z<-11);await held(page,'a',()=>window.__M1.player.x<.1);await held(page,'w',()=>window.__M1.player.z<-35);await page.locator('#interact').click();await until(page,()=>window.__M1.stage===2);assert.equal((await diagnostic(page)).interactionCount,2);await shot(page,'desktop-portal-vista.png');return (await diagnostic(page)).player;});
 await check('North world boundary blocks continued movement',async()=>{await held(page,'w',()=>window.__M1.player.z<-41.4);await page.keyboard.down('w');await page.waitForTimeout(1600);await page.keyboard.up('w');const d=await diagnostic(page);assert.ok(d.player.z>=-41.58-.001);assert.equal(d.blocked,false);return d.player;});
 await check('Solid building collision and camera obstruction',async()=>{await held(page,'s',()=>window.__M1.player.z>-30);await held(page,'d',()=>window.__M1.player.x>10.4);await page.keyboard.down('d');await page.waitForTimeout(1600);await page.keyboard.up('d');assert.ok((await diagnostic(page)).player.x<=10.58+.001);const center={x:480,y:400};await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x-262,center.y,{steps:6});await page.mouse.up();await until(page,()=>window.__M1.camera.clamped);const d=await diagnostic(page);assert.ok(d.camera.x<11);await shot(page,'desktop-camera-collision.png');return {player:d.player,camera:d.camera};});
 await check('Camera pitch and zoom stay bounded',async()=>{await page.mouse.move(450,380);await page.mouse.down();await page.mouse.move(450,2000,{steps:6});await page.mouse.up();await page.mouse.wheel(0,10000);await until(page,()=>window.__M1.camera.distance===10);let d=await diagnostic(page);assert.ok(d.camera.pitch<=1.03);assert.ok(d.camera.distance<=10);await page.mouse.wheel(0,-10000);await until(page,()=>window.__M1.camera.distance===3.5);d=await diagnostic(page);assert.ok(d.camera.distance>=3.5);return d.camera;});
 await check('Controls modal pauses movement and replay resets slice',async()=>{await page.getByRole('button',{name:'Open controls and settings'}).click();const before=(await diagnostic(page)).player;await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.up('w');assert.deepEqual((await diagnostic(page)).player,before);await page.getByLabel('Reduce arrival motion').check();await page.getByRole('button',{name:'Replay arrival'}).click();await until(page,()=>!window.__M1.intro);assert.equal((await diagnostic(page)).stage,0);assert.equal((await diagnostic(page)).player.z,11);});
 await check('Desktop performance sample',async()=>{await page.waitForTimeout(8000);const d=await diagnostic(page);const samples=d.fpsHistory.slice(-8);const mean=samples.reduce((a,b)=>a+b,0)/samples.length;measurements.desktop={viewport:d.viewport,meanFps:mean,minFps:Math.min(...samples),maxFps:Math.max(...samples),samples,drawCalls:d.drawCalls,triangles:d.triangles,geometries:d.geometries,textures:d.textures,pixelRatio:d.pixelRatio,quality:d.low?'Low':d.quality,renderer:d.renderer};return measurements.desktop;});
 await context.close();await browser.close();browser=await chromium.launch(launch);
 }
 // A new touch-enabled context provides mobile viewport, pointer type and real CDP touch events.
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));mobile.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());});mobile.setDefaultTimeout(90000);await mobile.goto('http://127.0.0.1:3210/');await mobile.getByRole('button',{name:'Enter the arrival zone'}).tap();await mobile.locator('#skip').tap();await until(mobile,()=>window.__M1.started&&!window.__M1.intro);
 const cdp=await mobileContext.newCDPSession(mobile);
 await check('Mobile controls visible and joystick moves',async()=>{assert.equal((await diagnostic(mobile)).touch,true);await mobile.locator('#joystick').waitFor({state:'visible'});const r=await mobile.locator('#joystick').boundingBox();const x=r.x+r.width/2,y=r.y+r.height/2;await touch(cdp,'touchStart',[point(x,y,1)]);await touch(cdp,'touchMove',[point(x,y-r.width*.30,1)]);await until(mobile,()=>window.__M1.player.z<9);await touch(cdp,'touchEnd',[]);const p=(await diagnostic(mobile)).player;await mobile.waitForTimeout(500);assert.deepEqual((await diagnostic(mobile)).player,p);await shot(mobile,'mobile-portrait.png');return {player:p,joystickSize:r.width};});
 await check('Simultaneous joystick movement and touch camera',async()=>{const r=await mobile.locator('#joystick').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;const before=await diagnostic(mobile);await touch(cdp,'touchStart',[point(x,y,1)]);await touch(cdp,'touchMove',[point(x,y-35,1)]);await touch(cdp,'touchStart',[point(x,y-35,1),point(315,400,2)]);await touch(cdp,'touchMove',[point(x,y-35,1),point(330,430,2)]);await until(mobile,()=>window.__M1.player.z<8);await touch(cdp,'touchEnd',[]);const after=await diagnostic(mobile);assert.notEqual(after.camera.yaw,before.camera.yaw);assert.notEqual(after.camera.pitch,before.camera.pitch);return {before:before.camera,after:after.camera,player:after.player};});
 await check('Portrait and landscape layouts fit and action targets remain usable',async()=>{for(const size of [{width:390,height:844},{width:844,height:390},{width:320,height:568}]){await mobile.setViewportSize(size);await until(mobile,()=>window.__M1.viewport.width===innerWidth);const layout=await mobile.evaluate(()=>{const ids=['joystick','interact','objective','help'];const rects=ids.map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,x:r.x,y:r.y,w:r.width,h:r.height};});return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,rects};});assert.ok(layout.scrollWidth<=layout.width);for(const r of layout.rects){assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=layout.width+1&&r.y+r.h<=layout.height+1,JSON.stringify(r));}const action=layout.rects.find(r=>r.id==='interact');assert.ok(action.w>=44&&action.h>=44);if(size.width===844)await shot(mobile,'mobile-landscape.png');}return {viewports:['390×844','844×390','320×568']};});
 await mobile.setViewportSize({width:390,height:844});
 await check('Mobile large action button completes beacon scan',async()=>{ // Reset camera/input through the normal replay UI, then move with touch.
 await mobile.locator('#help').tap();await mobile.getByLabel('Reduce arrival motion').check();await mobile.locator('#reset').tap();await until(mobile,()=>!window.__M1.intro); // camera yaw survives replay; rotate it back using actual touch input.
 const d=await diagnostic(mobile);if(Math.abs(d.camera.yaw)>.001){await touch(cdp,'touchStart',[point(310,420,2)]);await touch(cdp,'touchMove',[point(310+d.camera.yaw/.006,420,2)]);await touch(cdp,'touchEnd',[]);}
 const r=await mobile.locator('#joystick').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await touch(cdp,'touchStart',[point(x,y,1)]);await touch(cdp,'touchMove',[point(x,y-35,1)]);await until(mobile,()=>window.__M1.ready);await touch(cdp,'touchEnd',[]);await mobile.locator('#interact').tap();await until(mobile,()=>window.__M1.stage===1);await shot(mobile,'mobile-beacon.png');return {stage:(await diagnostic(mobile)).stage};});
 await check('Mobile software-renderer sample and capped pixel ratio',async()=>{const d=await diagnostic(mobile);assert.ok(d.pixelRatio<=1.35);measurements.mobileEmulation={viewport:d.viewport,fps:d.fps,frameMs:d.frameMs,drawCalls:d.drawCalls,triangles:d.triangles,pixelRatio:d.pixelRatio,quality:d.low?'Low':d.quality};return measurements.mobileEmulation;});
 await check('No fatal console or runtime errors',async()=>{assert.equal(errors.length,0);return {errors,warnings};});
 await mobileContext.close();completed=true;
}catch(e){console.error(e.message);results.push({name:'Browser runner completion',status:'FAIL',details:e.message});process.exitCode=1;}
finally{await browser?.close();server.kill();await writeFile('evidence/browser-results.json',JSON.stringify({completed,results,errors,warnings,measurements,screenshots},null,2));console.log('Saved evidence/browser-results.json');}
